# NLP Data Analysis

In [3]:
#pip install nltk

In [2]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

### Tokenization

In [7]:
text = "bu şehir bir başkadır. Herhkes beni aldattı gitti .kamyonlar yine kavun taşır fakat içimdeki şarkı bitti"

In [10]:
text.split() # text tokenization

['bu',
 'şehir',
 'bir',
 'başkadır.',
 'Herhkes',
 'beni',
 'aldattı',
 'gitti',
 '.kamyonlar',
 'yine',
 'kavun',
 'taşır',
 'fakat',
 'içimdeki',
 'şarkı',
 'bitti']

In [12]:
text.split('.') # sentence tokenization

['bu şehir bir başkadır',
 ' Herhkes beni aldattı gitti ',
 'kamyonlar yine kavun taşır fakat içimdeki şarkı bitti']

In [13]:
text.upper()

'BU ŞEHIR BIR BAŞKADIR. HERHKES BENI ALDATTI GITTI .KAMYONLAR YINE KAVUN TAŞIR FAKAT IÇIMDEKI ŞARKI BITTI'

In [16]:
from nltk.tokenize import word_tokenize, sent_tokenize , WordPunctTokenizer , TreebankWordTokenizer

In [17]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [21]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [22]:
word_tokenize(text)

['bu',
 'şehir',
 'bir',
 'başkadır',
 '.',
 'Herhkes',
 'beni',
 'aldattı',
 'gitti',
 '.kamyonlar',
 'yine',
 'kavun',
 'taşır',
 'fakat',
 'içimdeki',
 'şarkı',
 'bitti']

In [24]:
sent_tokenize(text)

['bu şehir bir başkadır.',
 'Herhkes beni aldattı gitti .kamyonlar yine kavun taşır fakat içimdeki şarkı bitti']

In [25]:
# Stopwords // am is are // gereksiz kelimeler

In [27]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [29]:
print(nltk.corpus.stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [ ]:
# Lemma ve Stemma ekleri kaldirip kokleri bulur

In [30]:
from nltk.stem import PorterStemmer

In [31]:
ps = PorterStemmer()

In [32]:
ps.stem('played')

'play'

In [33]:
liste = ['plays' , 'played' , 'went', 'took' , 'happiness']

In [37]:
[ps.stem(word)  for word in liste] # ekleri kaldırır

['play', 'play', 'went', 'took', 'happi']

In [38]:
from nltk import WordNetLemmatizer

In [39]:
wt = WordNetLemmatizer()

In [41]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...

True

In [43]:
[wt.lemmatize(word , 'v')  for word in liste]

['play', 'play', 'go', 'take', 'happiness']

In [45]:
from nltk.stem import LancasterStemmer

In [46]:
LancasterStemmer().stem('happiness')

'happy'

In [47]:
from nltk.stem import SnowballStemmer

In [52]:
ss = SnowballStemmer('spanish')

In [54]:
ss.stem('teqiero')

'teqier'

In [55]:
# POS - Part of Speech - Ozne yuklem nesne fiil subject verb object

In [56]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.

True

In [57]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.

True

In [58]:
cumle = 'work hard , do not procrestinate. welcome home . i hope you fşnd it interesting . please call me tonight'

In [60]:
cumlet= cumle.split()

In [61]:
nltk.pos_tag(cumlet)

[('work', 'NN'),
 ('hard', 'RB'),
 (',', ','),
 ('do', 'VBP'),
 ('not', 'RB'),
 ('procrestinate.', 'VB'),
 ('welcome', 'JJ'),
 ('home', 'NN'),
 ('.', '.'),
 ('i', 'VB'),
 ('hope', 'VBP'),
 ('you', 'PRP'),
 ('fşnd', 'VBP'),
 ('it', 'PRP'),
 ('interesting', 'JJ'),
 ('.', '.'),
 ('please', 'VB'),
 ('call', 'VB'),
 ('me', 'PRP'),
 ('tonight', 'JJ')]

In [64]:
pip install textblob==0.17.1

Collecting textblob==0.17.1
  Downloading textblob-0.17.1-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: nltk>=3.1 in c:\users\user\anaconda3\lib\site-packages (from textblob==0.17.1) (3.9.1)
Requirement already satisfied: click in c:\users\user\anaconda3\lib\site-packages (from nltk>=3.1->textblob==0.17.1) (8.1.8)
Requirement already satisfied: joblib in c:\users\user\anaconda3\lib\site-packages (from nltk>=3.1->textblob==0.17.1) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\user\anaconda3\lib\site-packages (from nltk>=3.1->textblob==0.17.1) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\user\anaconda3\lib\site-packages (from nltk>=3.1->textblob==0.17.1) (4.67.1)
Requirement already satisfied: colorama in c:\users\user\anaconda3\lib\site-packages (from click->nltk>=3.1->textblob==0.17.1) (0.4.6)
Downloading textblob-0.17.1-py2.py3-none-any.whl (636 kB)
   ---------------------------------------- 0.0/636.8 kB ? eta -:--:--
   -------------------------------- ------- 524.3/636.8 kB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 636.8/636.8 kB 6.2 MB/s eta 0:00:00
Installing collected packages: textblob
Successfully installed textblob-0.17.1
Note: you may need to restart the kernel to use updated packages.

In [65]:
from textblob import TextBlob

In [66]:
b = TextBlob('I havee goad spalling')

In [67]:
b.correct()

TextBlob("I have good spelling")

In [69]:
#pip install langdetect

In [71]:
from langdetect import detect

In [72]:
d = detect

In [73]:
d('Döndü dönmedi')

'tr'

In [75]:
d('i am doctor')

'ca'

In [76]:
# text blob çeviride yapabiliyor.

## NLP Introduction

1 Datayi okuma
2 Her şeyi küçük harfe çevir
3 Noktalama işaretlerini kaldir  Puntuation
4 Rakamları kaldır
5 Satır sonlarını kaldır
6 Stop Wordsleri kaldır - Gereksiz Kelimeler
7 Tokenize et
8 Ekleri kaldırıp kökleri bul
9 Vektörize et
10 TF/IDF Term frequency Inverse Document Frequency

In [77]:
text = ['Call you tonight', 'call me a cab', 'please call me ...  PLEASE']

In [79]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [80]:
vect = CountVectorizer()

In [82]:
vect.fit_transform(text).toarray()

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 2, 0, 0]])

In [83]:
import pandas as pd

In [85]:
tf = pd.DataFrame(vect.fit_transform(text).toarray() , columns = vect.get_feature_names_out())

In [86]:
tf

   cab  call  me  please  tonight  you
0    0     1   0       0        1    1
1    1     1   1       0        0    0
2    0     1   1       2        0    0

In [87]:
df = vect.fit_transform(text).toarray().sum(axis = 0)

In [88]:
df

array([1, 3, 2, 2, 1, 1])

In [89]:
tf/df

   cab      call   me  please  tonight  you
0  0.0  0.333333  0.0     0.0      1.0  1.0
1  1.0  0.333333  0.5     0.0      0.0  0.0
2  0.0  0.333333  0.5     1.0      0.0  0.0

In [90]:
df = pd.read_csv('yelp.csv')

In [91]:
df.head()

,business_id,date,review_id,stars,text,type,user_id,cool,useful,funny
0,9yKzy9PApeiPPOUJEtnvkg,2011-01-26,fWKvX83p0-ka4JS3dc6E5A,5,My wife took me here on my birthday for breakf...,review,rLtl8ZkDX5vH5nAx9C3q5Q,2,5,0
1,ZRJwVLyzEJq1VAihDhYiow,2011-07-27,IjZ33sJrzXqU-0X6U8NwyA,5,I have no idea why some people give bad review...,review,0a2KyEL0d3Yb1V6aivbIuQ,0,0,0
2,6oRAC4uyJCsJl1X0WZpVSA,2012-06-14,IESLBzqUCLdSzSqm0eCSxQ,4,love the gyro plate. Rice is so good and I als...,review,0hT2KtfLiobPvh6cDC8JQg,0,1,0
3,_1QQZuf4zZOyFCvXc0o6Vg,2010-05-27,G-WvGaISbqqaMHlNnByodA,5,"Rosie, Dakota, and I LOVE Chaparral Dog Park!!...",review,uZetl9T0NcROGOyFfughhg,1,2,0
4,6ozycU1RpktNG2-1BroVtw,2012-01-05,1uJFq2r5QfJG_6ExMRCaGw,5,General Manager Scott Petello is a good egg!!!...,review,vYmM4KTsC8ZfQBg-j5MWkw,0,0,0

In [92]:
df['text'][0]

'My wife took me here on my birthday for breakfast and it was excellent.  The weather was perfect which made sitting outside overlooking their grounds an absolute pleasure.  Our waitress was excellent and our food arrived quickly on the semi-busy Saturday morning.  It looked like the place fills up pretty quickly so the earlier you get here the better.\n\nDo yourself a favor and get their Bloody Mary.  It was phenomenal and simply the best I\'ve ever had.  I\'m pretty sure they only use ingredients from their garden and blend them fresh when you order it.  It was amazing.\n\nWhile EVERYTHING on the menu looks excellent, I had the white truffle scrambled eggs vegetable skillet and it was tasty and delicious.  It came with 2 pieces of their griddled bread with was amazing and it absolutely made the meal complete.  It was the best "toast" I\'ve ever had.\n\nAnyway, I can\'t wait to go back!'

In [96]:
df['text']=df['text'].str.lower() # küçük harf yapar
df['text']=df['text'].str.replace('[^\w\s]','',regex=True) # noktalama kaldır
df['text']=df['text'].str.replace('\d+','',regex=True) # rakamları kaldır
df['text']=df['text'].str.replace('\n','',regex=True) # satır sonlarını kaldır
df['text']=df['text'].str.replace('\r','',regex=True) # enterleri kaldır

In [97]:
df['text'][0]

'my wife took me here on my birthday for breakfast and it was excellent  the weather was perfect which made sitting outside overlooking their grounds an absolute pleasure  our waitress was excellent and our food arrived quickly on the semibusy saturday morning  it looked like the place fills up pretty quickly so the earlier you get here the betterdo yourself a favor and get their bloody mary  it was phenomenal and simply the best ive ever had  im pretty sure they only use ingredients from their garden and blend them fresh when you order it  it was amazingwhile everything on the menu looks excellent i had the white truffle scrambled eggs vegetable skillet and it was tasty and delicious  it came with  pieces of their griddled bread with was amazing and it absolutely made the meal complete  it was the best toast ive ever hadanyway i cant wait to go back'