# Titanic Veri Setini Derin Öğrenme kullanarak Çözeceğiz.

In [1]:
#pip install pandas

In [2]:
import pandas as pd

In [3]:
df_train = pd.read_csv('ttrain.csv')

In [4]:
df_test = pd.read_csv('ttest.csv')

## EDA

### 1) DF_Train

In [5]:
df_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
df_train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
df_train.shape

(891, 12)

In [9]:
df_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### 2) DF_Test

In [10]:
df_test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [11]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB

In [12]:
df_test.shape

(418, 11)

In [13]:
df_test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [14]:
# EDA işlemleri bitti

In [15]:
# Concat veri seti - test ve train setlerini birleştirip boş verileri doldurcaz

In [16]:
df = pd.concat([df_train , df_test])

In [17]:
df.corr(numeric_only = True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.038354,0.028814,-0.055224,0.008942,0.031428
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.038354,-0.338481,1.000000,-0.408106,0.060832,0.018322,-0.558629
Age,0.028814,-0.077221,-0.408106,1.000000,-0.243699,-0.150917,0.178740
SibSp,-0.055224,-0.035322,0.060832,-0.243699,1.000000,0.373587,0.160238
Parch,0.008942,0.081629,0.018322,-0.150917,0.373587,1.000000,0.221539
Fare,0.031428,0.257307,-0.558629,0.178740,0.160238,0.221539,1.000000

In [18]:
df.isnull().sum()

PassengerId       0
Survived        418
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

## Feature Engineering

In [19]:
del df['Cabin']

In [20]:
df.isnull().sum()

PassengerId      0
Survived       418
Pclass           0
Name             0
Sex              0
Age            263
SibSp            0
Parch            0
Ticket           0
Fare             1
Embarked         2
dtype: int64

In [21]:
del df['Name']

In [22]:
del df['Embarked']

In [23]:
del df['Ticket']

In [24]:
df.head()

   PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0            1       0.0       3    male  22.0      1      0   7.2500
1            2       1.0       1  female  38.0      1      0  71.2833
2            3       1.0       3  female  26.0      0      0   7.9250
3            4       1.0       1  female  35.0      1      0  53.1000
4            5       0.0       3    male  35.0      0      0   8.0500

In [25]:
df.isnull().sum()

PassengerId      0
Survived       418
Pclass           0
Sex              0
Age            263
SibSp            0
Parch            0
Fare             1
dtype: int64

### Fill blank with linear regression

In [26]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [27]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LinearRegression

In [28]:
lr=LinearRegression()
imp=IterativeImputer(estimator=lr)
imputed_data=imp.fit_transform(df[['Age']])

In [29]:
pd.DataFrame(imputed_data)

              0
0     22.000000
1     38.000000
2     26.000000
3     35.000000
4     35.000000
...         ...
1304  29.881138
1305  39.000000
1306  38.500000
1307  29.881138
1308  29.881138

[1309 rows x 1 columns]

In [30]:
df['Age'] = imputed_data

In [31]:
df.isnull().sum()

PassengerId      0
Survived       418
Pclass           0
Sex              0
Age              0
SibSp            0
Parch            0
Fare             1
dtype: int64

In [32]:
df.head()

   PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0            1       0.0       3    male  22.0      1      0   7.2500
1            2       1.0       1  female  38.0      1      0  71.2833
2            3       1.0       3  female  26.0      0      0   7.9250
3            4       1.0       1  female  35.0      1      0  53.1000
4            5       0.0       3    male  35.0      0      0   8.0500

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1309 entries, 0 to 417
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64
 3   Sex          1309 non-null   object
 4   Age          1309 non-null   float64
 5   SibSp        1309 non-null   int64
 6   Parch        1309 non-null   int64
 7   Fare         1308 non-null   float64
dtypes: float64(3), int64(4), object(1)
memory usage: 92.0+ KB

In [34]:
df.shape

(1309, 8)

In [35]:
lr=LinearRegression()
imp=IterativeImputer(estimator=lr)
imputed_data=imp.fit_transform(df[['Fare']])

In [36]:
pd.DataFrame(imputed_data)

             0
0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
...        ...
1304    8.0500
1305  108.9000
1306    7.2500
1307    8.0500
1308   22.3583

[1309 rows x 1 columns]

In [37]:
df['Fare'] = imputed_data

In [38]:
df.isnull().sum()

PassengerId      0
Survived       418
Pclass           0
Sex              0
Age              0
SibSp            0
Parch            0
Fare             0
dtype: int64

df.info

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1309 entries, 0 to 417
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64
 3   Sex          1309 non-null   object
 4   Age          1309 non-null   float64
 5   SibSp        1309 non-null   int64
 6   Parch        1309 non-null   int64
 7   Fare         1309 non-null   float64
dtypes: float64(3), int64(4), object(1)
memory usage: 92.0+ KB

In [40]:
## Get Dummies

In [41]:
df = pd.get_dummies(df ,drop_first  = True )

In [42]:
df.head()

   PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  Sex_male
0            1       0.0       3  22.0      1      0   7.2500      True
1            2       1.0       1  38.0      1      0  71.2833     False
2            3       1.0       3  26.0      0      0   7.9250     False
3            4       1.0       1  35.0      1      0  53.1000     False
4            5       0.0       3  35.0      0      0   8.0500      True

In [43]:
df.shape

(1309, 8)

### Normalization and Deep Learning

In [44]:
train = df[:891]
test = df[891:]

In [45]:
test['Survived'].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Survived, dtype: float64

In [46]:
x = train.drop('Survived','PassengerId', axis = 1)
y = train[['Survived']]

In [47]:
#pip install tensorflow

In [48]:
import tensorflow as tf

In [49]:
from tensorflow.keras.models import Sequential

In [50]:
from tensorflow.keras.layers import Dense

In [51]:
from sklearn.preprocessing import normalize, scale

In [52]:
from sklearn.preprocessing import StandardScaler

In [53]:
x = StandardScaler().fit_transform(x)

In [54]:
model = Sequential()
model.add(Dense(120, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='relu'))  
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [55]:
history = model.fit(x ,y , epochs = 300, batch_size = 32 , validation_split = 0.10 ,verbose = 1)

Epoch 1/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.6353 - loss: 0.5937 - val_accuracy: 0.8222 - val_loss: 0.5204
Epoch 2/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8092 - loss: 0.5107 - val_accuracy: 0.8222 - val_loss: 0.4923
Epoch 3/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7995 - loss: 0.5285 - val_accuracy: 0.8444 - val_loss: 0.4806
Epoch 4/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7961 - loss: 0.5195 - val_accuracy: 0.8111 - val_loss: 0.4773
Epoch 5/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8019 - loss: 0.5025 - val_accuracy: 0.8222 - val_loss: 0.4645
Epoch 6/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8019 - loss: 0.5036 - val_accuracy: 0.8444 - val_loss: 0.4661
Epoch 7/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8240 - loss: 0.4806 - val_accuracy: 0.8667 - val_loss: 0.4655
Epoch 8/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8484 - loss: 0.4547 - val_accuracy: 0.8222 - val_loss: 0.4465
Epoch 9/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8062 - loss: 0.5015 - val_accuracy: 0.8222 - val_loss: 0.4569
Epoch 10/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8460 - loss: 0.4648 - val_accuracy: 0.8111 - val_loss: 0.4519
Epoch 11/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8167 - loss: 0.4603 - val_accuracy: 0.8444 - val_loss: 0.4412
Epoch 12/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.8365 - loss: 0.4874 - val_accuracy: 0.8444 - val_loss: 0.4590
Epoch 13/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8292 - loss: 0.4525 - val_accuracy: 0.8444 - val_loss: 0.4416
Epoch 14/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8278 - loss: 0.4688 - val_accuracy: 0.8000 - val_loss: 0.4454
Epoch 15/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8245 - loss: 0.4942 - val_accuracy: 0.8333 - val_loss: 0.4608
Epoch 16/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8229 - loss: 0.4915 - val_accuracy: 0.8333 - val_loss: 0.4780
Epoch 17/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8645 - loss: 0.4249 - val_accuracy: 0.8333 - val_loss: 0.4398
Epoch 18/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8476 - loss: 0.4540 - val_accuracy: 0.8222 - val_loss: 0.4586
Epoch 19/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8427 - loss: 0.4692 - val_accuracy: 0.8333 - val_loss: 0.4611
Epoch 20/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8367 - loss: 0.4419 - val_accuracy: 0.8444 - val_loss: 0.4789
Epoch 21/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8360 - loss: 0.4414 - val_accuracy: 0.8333 - val_loss: 0.4575
Epoch 22/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8616 - loss: 0.4347 - val_accuracy: 0.8444 - val_loss: 0.5116
Epoch 23/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8564 - loss: 0.4164 - val_accuracy: 0.8222 - val_loss: 0.4537
Epoch 24/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8534 - loss: 0.4251 - val_accuracy: 0.8444 - val_loss: 0.5109
Epoch 25/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8461 - loss: 0.4087 - val_accuracy: 0.8222 - val_loss: 0.4327
Epoch 26/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8486 - loss: 0.4263 - val_accuracy: 0.8556 - val_loss: 0.4612
Epoch 27/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8624 - loss: 0.4079 - val_accuracy: 0.8444 - val_loss: 0.4621
Epoch 28/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8690 - loss: 0.3900 - val_accuracy: 0.8444 - val_loss: 0.4589
Epoch 29/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8561 - loss: 0.4025 - val_accuracy: 0.8333 - val_loss: 0.4693
Epoch 30/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8583 - loss: 0.4043 - val_accuracy: 0.8222 - val_loss: 0.4613
Epoch 31/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8512 - loss: 0.4148 - val_accuracy: 0.8444 - val_loss: 0.4929
Epoch 32/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8700 - loss: 0.4050 - val_accuracy: 0.8222 - val_loss: 0.4866
Epoch 33/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8682 - loss: 0.3724 - val_accuracy: 0.8444 - val_loss: 0.4670
Epoch 34/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8613 - loss: 0.3918 - val_accuracy: 0.8444 - val_loss: 0.4860
Epoch 35/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8758 - loss: 0.3697 - val_accuracy: 0.8111 - val_loss: 0.4788
Epoch 36/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8431 - loss: 0.4085 - val_accuracy: 0.8333 - val_loss: 0.5784
Epoch 37/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8449 - loss: 0.4269 - val_accuracy: 0.8333 - val_loss: 0.4688
Epoch 38/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8523 - loss: 0.3908 - val_accuracy: 0.8333 - val_loss: 0.4990
Epoch 39/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8576 - loss: 0.3972 - val_accuracy: 0.8333 - val_loss: 0.4809
Epoch 40/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8787 - loss: 0.3489 - val_accuracy: 0.8222 - val_loss: 0.5102
Epoch 41/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8653 - loss: 0.3653 - val_accuracy: 0.8333 - val_loss: 0.4698
Epoch 42/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8190 - loss: 0.4191 - val_accuracy: 0.8222 - val_loss: 0.5223
Epoch 43/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8511 - loss: 0.3859 - val_accuracy: 0.8444 - val_loss: 0.5391
Epoch 44/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8738 - loss: 0.3662 - val_accuracy: 0.8222 - val_loss: 0.4956
Epoch 45/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8767 - loss: 0.3498 - val_accuracy: 0.8333 - val_loss: 0.5346
Epoch 46/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8634 - loss: 0.3693 - val_accuracy: 0.8111 - val_loss: 0.4890
Epoch 47/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8549 - loss: 0.3731 - val_accuracy: 0.8333 - val_loss: 0.4953
Epoch 48/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8852 - loss: 0.3396 - val_accuracy: 0.8333 - val_loss: 0.5141
Epoch 49/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8651 - loss: 0.3796 - val_accuracy: 0.8222 - val_loss: 0.5077
Epoch 50/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8723 - loss: 0.3652 - val_accuracy: 0.8222 - val_loss: 0.5381
Epoch 51/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8830 - loss: 0.3342 - val_accuracy: 0.8222 - val_loss: 0.4904
Epoch 52/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8588 - loss: 0.3782 - val_accuracy: 0.8222 - val_loss: 0.5298
Epoch 53/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8785 - loss: 0.3458 - val_accuracy: 0.8333 - val_loss: 0.5362
Epoch 54/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8721 - loss: 0.3409 - val_accuracy: 0.8333 - val_loss: 0.5091
Epoch 55/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8684 - loss: 0.3526 - val_accuracy: 0.8222 - val_loss: 0.5581
Epoch 56/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8707 - loss: 0.3301 - val_accuracy: 0.8333 - val_loss: 0.4932
Epoch 57/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8229 - loss: 0.3909 - val_accuracy: 0.8111 - val_loss: 0.6116
Epoch 58/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8615 - loss: 0.3560 - val_accuracy: 0.8333 - val_loss: 0.5516
Epoch 59/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8619 - loss: 0.3539 - val_accuracy: 0.8333 - val_loss: 0.5493
Epoch 60/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8956 - loss: 0.3033 - val_accuracy: 0.8222 - val_loss: 0.5717
Epoch 61/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8721 - loss: 0.3399 - val_accuracy: 0.8444 - val_loss: 0.5015
Epoch 62/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8929 - loss: 0.2944 - val_accuracy: 0.8333 - val_loss: 0.5827
Epoch 63/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8762 - loss: 0.3199 - val_accuracy: 0.8333 - val_loss: 0.5365
Epoch 64/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.9043 - loss: 0.2976 - val_accuracy: 0.8000 - val_loss: 0.5646
Epoch 65/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.8817 - loss: 0.3034 - val_accuracy: 0.8333 - val_loss: 0.5217
Epoch 66/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8971 - loss: 0.3091 - val_accuracy: 0.8111 - val_loss: 0.5783
Epoch 67/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.8945 - loss: 0.2860 - val_accuracy: 0.8222 - val_loss: 0.5509
Epoch 68/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9031 - loss: 0.2838 - val_accuracy: 0.8000 - val_loss: 0.5990
Epoch 69/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8828 - loss: 0.3524 - val_accuracy: 0.8000 - val_loss: 0.5429
Epoch 70/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8084 - loss: 0.4162 - val_accuracy: 0.8111 - val_loss: 0.5232
Epoch 71/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8414 - loss: 0.3610 - val_accuracy: 0.8222 - val_loss: 0.5591
Epoch 72/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8476 - loss: 0.3578 - val_accuracy: 0.8222 - val_loss: 0.5799
Epoch 73/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8794 - loss: 0.3174 - val_accuracy: 0.8222 - val_loss: 0.5623
Epoch 74/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.8270 - loss: 0.3793 - val_accuracy: 0.8222 - val_loss: 0.5142
Epoch 75/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8713 - loss: 0.3478 - val_accuracy: 0.7889 - val_loss: 0.5269
Epoch 76/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.8566 - loss: 0.3537 - val_accuracy: 0.8000 - val_loss: 0.4893
Epoch 77/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8822 - loss: 0.3304 - val_accuracy: 0.8333 - val_loss: 0.4973
Epoch 78/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8682 - loss: 0.3336 - val_accuracy: 0.8222 - val_loss: 0.5586
Epoch 79/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8932 - loss: 0.2852 - val_accuracy: 0.8111 - val_loss: 0.5722
Epoch 80/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8932 - loss: 0.3022 - val_accuracy: 0.8222 - val_loss: 0.6292
Epoch 81/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.8747 - loss: 0.3102 - val_accuracy: 0.8222 - val_loss: 0.6228
Epoch 82/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8809 - loss: 0.3106 - val_accuracy: 0.8111 - val_loss: 0.6453
Epoch 83/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8946 - loss: 0.2799 - val_accuracy: 0.8000 - val_loss: 0.5800
Epoch 84/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.9125 - loss: 0.2657 - val_accuracy: 0.8000 - val_loss: 0.6400
Epoch 85/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8909 - loss: 0.3032 - val_accuracy: 0.8000 - val_loss: 0.6254
Epoch 86/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.8961 - loss: 0.2921 - val_accuracy: 0.8000 - val_loss: 0.6264
Epoch 87/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8855 - loss: 0.2929 - val_accuracy: 0.7889 - val_loss: 0.6340
Epoch 88/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8981 - loss: 0.2968 - val_accuracy: 0.8111 - val_loss: 0.6977
Epoch 89/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.8907 - loss: 0.2953 - val_accuracy: 0.8222 - val_loss: 0.5820
Epoch 90/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9080 - loss: 0.2768 - val_accuracy: 0.7889 - val_loss: 0.6344
Epoch 91/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.8878 - loss: 0.2893 - val_accuracy: 0.8111 - val_loss: 0.6107
Epoch 92/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9151 - loss: 0.2514 - val_accuracy: 0.8000 - val_loss: 0.6520
Epoch 93/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.9064 - loss: 0.2673 - val_accuracy: 0.8111 - val_loss: 0.5827
Epoch 94/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.9151 - loss: 0.2554 - val_accuracy: 0.8000 - val_loss: 0.6688
Epoch 95/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.9059 - loss: 0.2680 - val_accuracy: 0.8000 - val_loss: 0.6663
Epoch 96/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.9129 - loss: 0.2573 - val_accuracy: 0.8000 - val_loss: 0.6124
Epoch 97/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.8968 - loss: 0.2762 - val_accuracy: 0.8111 - val_loss: 0.5912
Epoch 98/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.9222 - loss: 0.2342 - val_accuracy: 0.8222 - val_loss: 0.6758
Epoch 99/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.9036 - loss: 0.2753 - val_accuracy: 0.8111 - val_loss: 0.7506
Epoch 100/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.9030 - loss: 0.2742 - val_accuracy: 0.7889 - val_loss: 0.7925
Epoch 101/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.9040 - loss: 0.2807 - val_accuracy: 0.8000 - val_loss: 0.6855
Epoch 102/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.9148 - loss: 0.2488 - val_accuracy: 0.8000 - val_loss: 0.6817
Epoch 103/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.9183 - loss: 0.2484 - val_accuracy: 0.8000 - val_loss: 0.6908
Epoch 104/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.9055 - loss: 0.2554 - val_accuracy: 0.8000 - val_loss: 0.6150
Epoch 105/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.8955 - loss: 0.2852 - val_accuracy: 0.8000 - val_loss: 0.7544
Epoch 106/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.9076 - loss: 0.2568 - val_accuracy: 0.8111 - val_loss: 0.6352
Epoch 107/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.8960 - loss: 0.2734 - val_accuracy: 0.8000 - val_loss: 0.8195
Epoch 108/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.8927 - loss: 0.2945 - val_accuracy: 0.8111 - val_loss: 0.6485
Epoch 109/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.8728 - loss: 0.3041 - val_accuracy: 0.8000 - val_loss: 0.6447
Epoch 110/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.8963 - loss: 0.2953 - val_accuracy: 0.8222 - val_loss: 0.6605
Epoch 111/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.8960 - loss: 0.2956 - val_accuracy: 0.8000 - val_loss: 0.8241
Epoch 112/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.9045 - loss: 0.2808 - val_accuracy: 0.8222 - val_loss: 0.5911
Epoch 113/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.9061 - loss: 0.2670 - val_accuracy: 0.8111 - val_loss: 0.6490
Epoch 114/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.8986 - loss: 0.2846 - val_accuracy: 0.8111 - val_loss: 0.6465
Epoch 115/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9110 - loss: 0.2702 - val_accuracy: 0.8111 - val_loss: 0.6446
Epoch 116/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9139 - loss: 0.2481 - val_accuracy: 0.8000 - val_loss: 0.6770
Epoch 117/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.9115 - loss: 0.2498 - val_accuracy: 0.8333 - val_loss: 0.5630
Epoch 118/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9179 - loss: 0.2401 - val_accuracy: 0.8444 - val_loss: 0.6344
Epoch 119/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9211 - loss: 0.2176 - val_accuracy: 0.8333 - val_loss: 0.6110
Epoch 120/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.8892 - loss: 0.2788 - val_accuracy: 0.8000 - val_loss: 0.7156
Epoch 121/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9145 - loss: 0.2538 - val_accuracy: 0.8000 - val_loss: 0.7838
Epoch 122/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.9212 - loss: 0.2217 - val_accuracy: 0.8000 - val_loss: 0.8609
Epoch 123/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9029 - loss: 0.2612 - val_accuracy: 0.8111 - val_loss: 0.6661
Epoch 124/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.8996 - loss: 0.2685 - val_accuracy: 0.8111 - val_loss: 0.8274
Epoch 125/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.8661 - loss: 0.3149 - val_accuracy: 0.8000 - val_loss: 0.7547
Epoch 126/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9104 - loss: 0.2487 - val_accuracy: 0.8111 - val_loss: 0.7293
Epoch 127/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9051 - loss: 0.2502 - val_accuracy: 0.8000 - val_loss: 0.7643
Epoch 128/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9035 - loss: 0.2619 - val_accuracy: 0.8000 - val_loss: 0.7928
Epoch 129/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9193 - loss: 0.2305 - val_accuracy: 0.8000 - val_loss: 0.8569
Epoch 130/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9145 - loss: 0.2063 - val_accuracy: 0.7889 - val_loss: 0.8199
Epoch 131/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9193 - loss: 0.2192 - val_accuracy: 0.7889 - val_loss: 0.8597
Epoch 132/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9254 - loss: 0.1991 - val_accuracy: 0.8000 - val_loss: 0.8565
Epoch 133/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9196 - loss: 0.2110 - val_accuracy: 0.8000 - val_loss: 0.9175
Epoch 134/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9102 - loss: 0.2328 - val_accuracy: 0.7889 - val_loss: 0.8562
Epoch 135/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9094 - loss: 0.2368 - val_accuracy: 0.8111 - val_loss: 0.8921
Epoch 136/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9016 - loss: 0.2539 - val_accuracy: 0.7889 - val_loss: 1.0128
Epoch 137/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9136 - loss: 0.2213 - val_accuracy: 0.8000 - val_loss: 0.6972
Epoch 138/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8995 - loss: 0.2489 - val_accuracy: 0.8000 - val_loss: 0.9007
Epoch 139/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.9220 - loss: 0.2032 - val_accuracy: 0.7889 - val_loss: 0.8882
Epoch 140/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9267 - loss: 0.1875 - val_accuracy: 0.8000 - val_loss: 0.9363
Epoch 141/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9153 - loss: 0.1971 - val_accuracy: 0.8000 - val_loss: 0.8129
Epoch 142/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9003 - loss: 0.2111 - val_accuracy: 0.8000 - val_loss: 0.8761
Epoch 143/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9289 - loss: 0.1864 - val_accuracy: 0.8000 - val_loss: 0.9392
Epoch 144/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9013 - loss: 0.2187 - val_accuracy: 0.8000 - val_loss: 0.9018
Epoch 145/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9115 - loss: 0.2115 - val_accuracy: 0.8000 - val_loss: 0.8665
Epoch 146/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9032 - loss: 0.2290 - val_accuracy: 0.8000 - val_loss: 0.9285
Epoch 147/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9274 - loss: 0.1813 - val_accuracy: 0.8000 - val_loss: 0.9415
Epoch 148/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9057 - loss: 0.2150 - val_accuracy: 0.7889 - val_loss: 1.0588
Epoch 149/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.9117 - loss: 0.2040 - val_accuracy: 0.8000 - val_loss: 0.9557
Epoch 150/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.9042 - loss: 0.2142 - val_accuracy: 0.7889 - val_loss: 0.8970
Epoch 151/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9116 - loss: 0.2020 - val_accuracy: 0.8111 - val_loss: 1.0765
Epoch 152/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9155 - loss: 0.1917 - val_accuracy: 0.8000 - val_loss: 0.9445
Epoch 153/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9127 - loss: 0.2028 - val_accuracy: 0.8000 - val_loss: 0.9503
Epoch 154/300
26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.9109 - loss: 0.1975 - val_accuracy: 0.8000 - val_loss: 1.0711
Epoch 155/300

In [80]:
x_test = test.drop(['Survived'], axis=1)
y_test = test[['Survived']]

In [81]:
# Test verisi ile modelin doğruluğunu değerlendirme
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print(f'Test Kaybı: {test_loss}, Test Doğruluğu: {test_accuracy}')

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 5.5917e-23
Test Kaybı: 5.137217147081014e-23, Test Doğruluğu: 1.0

In [93]:
# Yeni veriler üzerinde tahmin yapma
predictions = model.predict(x_test)

# Tahmin sonuçlarını gösterme
print(predictions[:10])  # İlk 10 tahmini göster

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [101]:
df4=pd.DataFrame(predictions)

In [102]:
df4.value_counts()

0
0.0    399
1.0     19
Name: count, dtype: int64

In [103]:
test.shape

(418, 8)

In [104]:
test['Survived'] = df4

In [105]:
test.head()

   PassengerId  Pclass   Age  SibSp  Parch     Fare  Sex_male  Survived
0          892       3  34.5      0      0   7.8292      True       0.0
1          893       3  47.0      1      0   7.0000     False       0.0
2          894       2  62.0      0      0   9.6875      True       0.0
3          895       3  27.0      0      0   8.6625      True       0.0
4          896       3  22.0      1      1  12.2875     False       0.0

In [106]:
test[['PassengerId', 'Survived']].to_csv('submission.csv', index=False)

In [107]:
result = pd.read_csv('submission.csv')

In [108]:
result.shape

(418, 2)

In [109]:
result.head()

   PassengerId  Survived
0          892       0.0
1          893       0.0
2          894       0.0
3          895       0.0
4          896       0.0

In [ ]:
pd.valu