# Titanic Veri Setini Derin Öğrenme kullanarak Çözeceğiz.

In [1]:
#pip install pandas

In [2]:
import pandas as pd

In [3]:
df_train = pd.read_csv('ttrain.csv')

In [4]:
df_test = pd.read_csv('ttest.csv')

## EDA

### 1) DF_Train

In [5]:
df_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
df_train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
df_train.shape

(891, 12)

In [9]:
df_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### 2) DF_Test

In [10]:
df_test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [11]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB

In [12]:
df_test.shape

(418, 11)

In [13]:
df_test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [14]:
# EDA işlemleri bitti

In [15]:
# Concat veri seti - test ve train setlerini birleştirip boş verileri doldurcaz

In [16]:
df = pd.concat([df_train , df_test])

In [17]:
df.corr(numeric_only = True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.038354,0.028814,-0.055224,0.008942,0.031428
Survived,-0.005007,1.000000,-0.338481,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.038354,-0.338481,1.000000,-0.408106,0.060832,0.018322,-0.558629
Age,0.028814,-0.077221,-0.408106,1.000000,-0.243699,-0.150917,0.178740
SibSp,-0.055224,-0.035322,0.060832,-0.243699,1.000000,0.373587,0.160238
Parch,0.008942,0.081629,0.018322,-0.150917,0.373587,1.000000,0.221539
Fare,0.031428,0.257307,-0.558629,0.178740,0.160238,0.221539,1.000000

In [18]:
df.isnull().sum()

PassengerId       0
Survived        418
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

## Feature Engineering

In [19]:
del df['Cabin']

In [20]:
df.isnull().sum()

PassengerId      0
Survived       418
Pclass           0
Name             0
Sex              0
Age            263
SibSp            0
Parch            0
Ticket           0
Fare             1
Embarked         2
dtype: int64

In [21]:
del df['Name']

In [22]:
del df['Embarked']

In [23]:
del df['Ticket']

In [24]:
df.head()

   PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0            1       0.0       3    male  22.0      1      0   7.2500
1            2       1.0       1  female  38.0      1      0  71.2833
2            3       1.0       3  female  26.0      0      0   7.9250
3            4       1.0       1  female  35.0      1      0  53.1000
4            5       0.0       3    male  35.0      0      0   8.0500

In [25]:
df.isnull().sum()

PassengerId      0
Survived       418
Pclass           0
Sex              0
Age            263
SibSp            0
Parch            0
Fare             1
dtype: int64

### Fill blank with linear regression

In [26]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [27]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LinearRegression

In [28]:
lr=LinearRegression()
imp=IterativeImputer(estimator=lr)
imputed_data=imp.fit_transform(df[['Age']])

In [29]:
pd.DataFrame(imputed_data)

              0
0     22.000000
1     38.000000
2     26.000000
3     35.000000
4     35.000000
...         ...
1304  29.881138
1305  39.000000
1306  38.500000
1307  29.881138
1308  29.881138

[1309 rows x 1 columns]

In [30]:
df['Age'] = imputed_data

In [31]:
df.isnull().sum()

PassengerId      0
Survived       418
Pclass           0
Sex              0
Age              0
SibSp            0
Parch            0
Fare             1
dtype: int64

In [32]:
df.head()

   PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0            1       0.0       3    male  22.0      1      0   7.2500
1            2       1.0       1  female  38.0      1      0  71.2833
2            3       1.0       3  female  26.0      0      0   7.9250
3            4       1.0       1  female  35.0      1      0  53.1000
4            5       0.0       3    male  35.0      0      0   8.0500

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1309 entries, 0 to 417
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64
 3   Sex          1309 non-null   object
 4   Age          1309 non-null   float64
 5   SibSp        1309 non-null   int64
 6   Parch        1309 non-null   int64
 7   Fare         1308 non-null   float64
dtypes: float64(3), int64(4), object(1)
memory usage: 92.0+ KB

In [34]:
df.shape

(1309, 8)

In [35]:
lr=LinearRegression()
imp=IterativeImputer(estimator=lr)
imputed_data=imp.fit_transform(df[['Fare']])

In [36]:
pd.DataFrame(imputed_data)

             0
0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
...        ...
1304    8.0500
1305  108.9000
1306    7.2500
1307    8.0500
1308   22.3583

[1309 rows x 1 columns]

In [37]:
df['Fare'] = imputed_data

In [38]:
df.isnull().sum()

PassengerId      0
Survived       418
Pclass           0
Sex              0
Age              0
SibSp            0
Parch            0
Fare             0
dtype: int64

df.info

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1309 entries, 0 to 417
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64
 3   Sex          1309 non-null   object
 4   Age          1309 non-null   float64
 5   SibSp        1309 non-null   int64
 6   Parch        1309 non-null   int64
 7   Fare         1309 non-null   float64
dtypes: float64(3), int64(4), object(1)
memory usage: 92.0+ KB

In [40]:
## Get Dummies

In [41]:
df = pd.get_dummies(df ,drop_first  = True )

In [42]:
df.head()

   PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  Sex_male
0            1       0.0       3  22.0      1      0   7.2500      True
1            2       1.0       1  38.0      1      0  71.2833     False
2            3       1.0       3  26.0      0      0   7.9250     False
3            4       1.0       1  35.0      1      0  53.1000     False
4            5       0.0       3  35.0      0      0   8.0500      True

In [43]:
df.shape

(1309, 8)

### Normalization and Deep Learning

In [44]:
x = df.drop('Survived', axis = 1)
y = df[['Survived']]

In [46]:
pip install tensorflow

Collecting tensorflow
  Using cached tensorflow-2.19.0-cp39-cp39-win_amd64.whl.metadata (4.1 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Using cached absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=24.3.25 (from tensorflow)
  Using cached flatbuffers-25.2.10-py2.py3-none-any.whl.metadata (875 bytes)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
Collecting google-pasta>=0.1.1 (from tensorflow)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt-einsum>=2.3.2 (from tensorflow)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from tensorflow) (25.0)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 (from tensorflow)
  Using cached protobuf-5.29.5-cp39-cp39-win_amd64.whl.metadata (592 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from tensorflow) (78.1.1)
Requirement already satisfied: six>=1.12.0 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Using cached termcolor-3.1.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from tensorflow) (4.14.1)
Collecting wrapt>=1.11.0 (from tensorflow)
  Using cached wrapt-1.17.2-cp39-cp39-win_amd64.whl.metadata (6.5 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Using cached grpcio-1.74.0-cp39-cp39-win_amd64.whl.metadata (4.0 kB)
Collecting tensorboard~=2.19.0 (from tensorflow)
  Using cached tensorboard-2.19.0-py3-none-any.whl.metadata (1.8 kB)
Collecting keras>=3.5.0 (from tensorflow)
  Using cached keras-3.10.0-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from tensorflow) (2.0.2)
Collecting h5py>=3.11.0 (from tensorflow)
  Using cached h5py-3.14.0-cp39-cp39-win_amd64.whl.metadata (2.7 kB)
Collecting ml-dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Using cached ml_dtypes-0.5.3-cp39-cp39-win_amd64.whl.metadata (9.2 kB)
Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow)
  Using cached tensorflow_io_gcs_filesystem-0.31.0-cp39-cp39-win_amd64.whl.metadata (14 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.7.14)
Collecting markdown>=2.6.8 (from tensorboard~=2.19.0->tensorflow)
  Using cached markdown-3.8.2-py3-none-any.whl.metadata (5.1 kB)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard~=2.19.0->tensorflow)
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard~=2.19.0->tensorflow)
  Using cached werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Collecting rich (from keras>=3.5.0->tensorflow)
  Using cached rich-14.1.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras>=3.5.0->tensorflow)
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.5.0->tensorflow)
  Using cached optree-0.17.0-cp39-cp39-win_amd64.whl.metadata (34 kB)
Requirement already satisfied: importlib-metadata>=4.4 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from markdown>=2.6.8->tensorboard~=2.19.0->tensorflow) (8.7.0)
Requirement already satisfied: zipp>=3.20 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard~=2.19.0->tensorflow) (3.23.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.2)
Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.5.0->tensorflow)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\melih\anaconda3\envs\myenv\lib\site-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading tensorflow-2.19.0-cp39-cp39-win_amd64.whl (375.7 MB)
   ---------------------------------------- 0.0/375.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/375.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/375.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/375.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/375.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/375.7 MB 799.2 kB/s eta 0:07:50
   ---------------------------------------- 0.5/375.7 MB 799.2 kB/s eta 0:07:50
   ---------------------------------------- 0.8/375.7 MB 884.1 kB/s eta 0:07:05
   ---------------------------------------- 1.0/375.7 MB 932.9 kB/s eta 0:06:42
   ---------------------------------------- 1.3/375.7 MB 1.0 MB/s eta 0:06:09
   ---------------------------------------- 1.6/375.7 MB 1.0 MB/s eta 0:05:57
   ---------------------------------------- 2.1/375.7 MB 1.1 MB/s eta 0:05:34
   ---------------------------------------- 2.1/375.7 MB 1.1 MB/s eta 0:05:34
   ---------------------------------------- 2.6/375.7 MB 1.2 MB/s eta 0:05:19
   ---------------------------------------- 2.9/375.7 MB 1.2 MB/s eta 0:05:14
   ---------------------------------------- 3.1/375.7 MB 1.2 MB/s eta 0:05:07
   ---------------------------------------- 3.1/375.7 MB 1.2 MB/s eta 0:05:07
   ---------------------------------------- 3.9/375.7 MB 1.3 MB/s eta 0:04:56
   ---------------------------------------- 3.9/375.7 MB 1.3 MB/s eta 0:04:56
   ---------------------------------------- 4.5/375.7 MB 1.2 MB/s eta 0:04:58
    --------------------------------------- 4.7/375.7 MB 1.2 MB/s eta 0:05:00
    --------------------------------------- 5.0/375.7 MB 1.2 MB/s eta 0:05:00
    --------------------------------------- 5.2/375.7 MB 1.2 MB/s eta 0:04:58
    --------------------------------------- 5.5/375.7 MB 1.2 MB/s eta 0:04:58
    --------------------------------------- 5.8/375.7 MB 1.2 MB/s eta 0:04:57
    --------------------------------------- 6.0/375.7 MB 1.3 MB/s eta 0:04:56
    --------------------------------------- 6.0/375.7 MB 1.3 MB/s eta 0:04:56
    --------------------------------------- 6.6/375.7 MB 1.3 MB/s eta 0:04:55
    --------------------------------------- 6.8/375.7 MB 1.2 MB/s eta 0:04:58
    --------------------------------------- 7.1/375.7 MB 1.2 MB/s eta 0:04:58
    --------------------------------------- 7.1/375.7 MB 1.2 MB/s eta 0:04:58
    --------------------------------------- 7.3/375.7 MB 1.2 MB/s eta 0:05:01
    --------------------------------------- 7.6/375.7 MB 1.2 MB/s eta 0:05:02
    --------------------------------------- 7.9/375.7 MB 1.2 MB/s eta 0:05:04
    --------------------------------------- 8.1/375.7 MB 1.2 MB/s eta 0:05:04
    --------------------------------------- 8.4/375.7 MB 1.2 MB/s eta 0:05:05
    --------------------------------------- 8.7/375.7 MB 1.2 MB/s eta 0:05:06
    --------------------------------------- 8.9/375.7 MB 1.2 MB/s eta 0:05:05
    --------------------------------------- 9.2/375.7 MB 1.2 MB/s eta 0:05:06
   - -------------------------------------- 9.4/375.7 MB 1.2 MB/s eta 0:05:06
   - -------------------------------------- 9.7/375.7 MB 1.2 MB/s eta 0:05:06
   - -------------------------------------- 10.0/375.7 MB 1.2 MB/s eta 0:05:06
   - -------------------------------------- 10.2/375.7 MB 1.2 MB/s eta 0:05:07
   - -------------------------------------- 10.5/375.7 MB 1.2 MB/s eta 0:05:05
   - -------------------------------------- 10.7/375.7 MB 1.2 MB/s eta 0:05:06
   - -------------------------------------- 11.0/375.7 MB 1.2 MB/s eta 0:05:06
   - -------------------------------------- 11.0/375.7 MB 1.2 MB/s eta 0:05:06
   - -------------------------------------- 11.0/375.7 MB 1.2 MB/s eta 0:05:06
   - -------------------------------------- 11.5/375.7 MB 1.2 MB/s eta 0:05:07
   - -------------------------------------- 11.8/375.7 MB 1.2 MB/s eta 0:05:08
   - -------------------------------------- 12.1/375.7 MB 1.2 MB/s eta 0:05:10
   - -------------------------------------- 12.1/375.7 MB 1.2 MB/s eta 0:05:10
   - -------------------------------------- 12.3/375.7 MB 1.2 MB/s eta 0:05:12
   - -------------------------------------- 12.6/375.7 MB 1.2 MB/s eta 0:05:12
   - -------------------------------------- 12.8/375.7 MB 1.2 MB/s eta 0:05:14
   - -------------------------------------- 12.8/375.7 MB 1.2 MB/s eta 0:05:14
   - -------------------------------------- 13.1/375.7 MB 1.1 MB/s eta 0:05:21
   - -------------------------------------- 13.4/375.7 MB 1.1 MB/s eta 0:05:16
   - -------------------------------------- 13.6/375.7 MB 1.1 MB/s eta 0:05:20
   - -------------------------------------- 13.6/375.7 MB 1.1 MB/s eta 0:05:20
   - -------------------------------------- 13.9/375.7 MB 1.1 MB/s eta 0:05:22
   - -------------------------------------- 14.2/375.7 MB 1.1 MB/s eta 0:05:24
   - -------------------------------------- 14.2/375.7 MB 1.1 MB/s eta 0:05:24
   - -------------------------------------- 14.2/375.7 MB 1.1 MB/s eta 0:05:24
   - -------------------------------------- 14.4/375.7 MB 1.1 MB/s eta 0:05:33
   - -------------------------------------- 14.7/375.7 MB 1.1 MB/s eta 0:05:29
   - -------------------------------------- 14.7/375.7 MB 1.1 MB/s eta 0:05:29
   - -------------------------------------- 14.9/375.7 MB 1.1 MB/s eta 0:05:34
   - -------------------------------------- 14.9/375.7 MB 1.1 MB/s eta 0:05:34
   - -------------------------------------- 15.2/375.7 MB 1.1 MB/s eta 0:05:38
   - -------------------------------------- 15.2/375.7 MB 1.1 MB/s eta 0:05:38
   - -------------------------------------- 15.5/375.7 MB 1.1 MB/s eta 0:05:42
   - -------------------------------------- 15.7/375.7 MB 1.0 MB/s eta 0:05:45
   - -------------------------------------- 15.7/375.7 MB 1.0 MB/s eta 0:05:45
   - -------------------------------------- 16.0/375.7 MB 1.0 MB/s eta 0:05:47
   - -------------------------------------- 16.0/375.7 MB 1.0 MB/s eta 0:05:47
   - -------------------------------------- 16.3/375.7 MB 1.0 MB/s eta 0:05:50
   - -------------------------------------- 16.3/375.7 MB 1.0 MB/s eta 0:05:50
   - -------------------------------------- 16.5/375.7 MB 1.0 MB/s eta 0:05:52
   - -------------------------------------- 16.8/375.7 MB 1.0 MB/s eta 0:05:54
   - -------------------------------------- 16.8/375.7 MB 1.0 MB/s eta 0:05:54
   - -------------------------------------- 17.0/375.7 MB 1.0 MB/s eta 0:05:57
   - -------------------------------------- 17.0/375.7 MB 1.0 MB/s eta 0:05:57
   - -------------------------------------- 17.3/375.7 MB 1.0 MB/s eta 0:05:58
   - ------------------------------------- 17.6/375.7 MB 994.9 kB/s eta 0:06:00
   - ------------------------------------- 17.6/375.7 MB 994.9 kB/s eta 0:06:00
   - ------------------------------------- 17.8/375.7 MB 987.8 kB/s eta 0:06:03
   - ------------------------------------- 17.8/375.7 MB 987.8 kB/s eta 0:06:03
   - ------------------------------------- 18.1/375.7 MB 982.7 kB/s eta 0:06:04
   - ------------------------------------- 18.1/375.7 MB 982.7 kB/s eta 0:06:04
   - ------------------------------------- 18.4/375.7 MB 976.9 kB/s eta 0:06:06
   - ------------------------------------- 18.6/375.7 MB 971.4 kB/s eta 0:06:08
   - ------------------------------------- 18.6/375.7 MB 971.4 kB/s eta 0:06:08
   - ------------------------------------- 18.9/375.7 MB 965.3 kB/s eta 0:06:10
   - ------------------------------------- 18.9/375.7 MB 965.3 kB/s eta 0:06:10
   - ------------------------------------- 19.1/375.7 MB 961.0 kB/s eta 0:06:12
   - ------------------------------------- 19.1/375.7 MB 961.0 kB/s eta 0:06:12
   -- ------------------------------------ 19.4/375.7 MB 956.8 kB/s eta 0:06:13
   -- ------------------------------------ 19.7/375.7 MB 952.1 kB/s eta 0:06:14
   -- ------------------------------------ 19.7/375.7 MB 952.1 kB/s eta 0:06:14
   -- ------------------------------------ 19.9/375.7 MB 944.7 kB/s eta 0:06:17
   -- ------------------------------------ 19.9/375.7 MB 944.7 kB/s eta 0:06:17
   -- ------------------------------------ 20.2/375.7 MB 941.0 kB/s eta 0:06:18
   -- ------------------------------------ 20.2/375.7 MB 941.0 kB/s eta 0:06:18
   -- ------------------------------------ 20.4/375.7 MB 934.1 kB/s eta 0:06:21
   -- ------------------------------------ 20.4/375.7 MB 934.1 kB/s eta 0:06:21
   -- ------------------------------------ 20.7/375.7 MB 928.1 kB/s eta 0:06:23
   -- ------------------------------------ 20.7/375.7 MB 928.1 kB/s eta 0:06:23
   -- ------------------------------------ 20.7/375.7 MB 928.1 kB/s eta 0:06:23
   -- ------------------------------------ 21.0/375.7 MB 915.3 kB/s eta 0:06:28
   -- ------------------------------------ 21.2/375.7 MB 916.8 kB/s eta 0:06:27
   -- ------------------------------------ 21.2/375.7 MB 916.8 kB/s eta 0:06:27
   -- ------------------------------------ 21.5/375.7 MB 906.6 kB/s eta 0:06:31
   -- ------------------------------------ 21.5/375.7 MB 906.6 kB/s eta 0:06:31
   -- ------------------------------------ 21.5/375.7 MB 906.6 kB/s eta 0:06:31
   -- ------------------------------------ 21.8/375.7 MB 899.2 kB/s eta 0:06:34
   -- ------------------------------------ 21.8/375.7 MB 899.2 kB/s eta 0:06:34
   -- ------------------------------------ 22.0/375.7 MB 892.1 kB/s eta 0:06:37
   -- ------------------------------------ 22.0/375.7 MB 892.1 kB/s eta 0:06:37
   -- ------------------------------------ 22.3/375.7 MB 886.4 kB/s eta 0:06:39
   -- ------------------------------------ 22.3/375.7 MB 886.4 kB/s eta 0:06:39
   -- ------------------------------------ 22.5/375.7 MB 880.9 kB/s eta 0:06:41
   -- ------------------------------------ 22.5/375.7 MB 880.9 kB/s eta 0:06:41
   -- ------------------------------------ 22.8/375.7 MB 875.0 kB/s eta 0:06:44
   -- ------------------------------------ 22.8/375.7 MB 875.0 kB/s eta 0:06:44
   -- ------------------------------------ 23.1/375.7 MB 869.4 kB/s eta 0:06:46
   -- ------------------------------------ 23.1/375.7 MB 869.4 kB/s eta 0:06:46
   -- ------------------------------------ 23.3/375.7 MB 865.4 kB/s eta 0:06:48
   -- ------------------------------------ 23.3/375.7 MB 865.4 kB/s eta 0:06:48
   -- ------------------------------------ 23.6/375.7 MB 860.1 kB/s eta 0:06:50
   -- ------------------------------------ 23.6/375.7 MB 860.1 kB/s eta 0:06:50
   -- ------------------------------------ 23.9/375.7 MB 855.5 kB/s eta 0:06:52
   -- ------------------------------------ 23.9/375.7 MB 855.5 kB/s eta 0:06:52
   -- ------------------------------------ 23.9/375.7 MB 855.5 kB/s eta 0:06:52
   -- ------------------------------------ 24.1/375.7 MB 851.0 kB/s eta 0:06:54
   -- ------------------------------------ 24.1/375.7 MB 851.0 kB/s eta 0:06:54
   -- ------------------------------------ 24.4/375.7 MB 846.7 kB/s eta 0:06:55
   -- ------------------------------------ 24.4/375.7 MB 846.7 kB/s eta 0:06:55
   -- ------------------------------------ 24.6/375.7 MB 842.5 kB/s eta 0:06:57
   -- ------------------------------------ 24.6/375.7 MB 842.5 kB/s eta 0:06:57
   -- ------------------------------------ 24.9/375.7 MB 838.9 kB/s eta 0:06:59
   -- ------------------------------------ 24.9/375.7 MB 838.9 kB/s eta 0:06:59
   -- ------------------------------------ 25.2/375.7 MB 836.2 kB/s eta 0:07:00
   -- ------------------------------------ 25.2/375.7 MB 836.2 kB/s eta 0:07:00
   -- ------------------------------------ 25.4/375.7 MB 833.6 kB/s eta 0:07:01
   -- ------------------------------------ 25.4/375.7 MB 833.6 kB/s eta 0:07:01
   -- ------------------------------------ 25.7/375.7 MB 827.4 kB/s eta 0:07:04
   -- ------------------------------------ 26.0/375.7 MB 822.2 kB/s eta 0:07:06
   -- ------------------------------------ 26.0/375.7 MB 822.2 kB/s eta 0:07:06
   -- ------------------------------------ 26.2/375.7 MB 815.2 kB/s eta 0:07:09
   -- ------------------------------------ 26.2/375.7 MB 815.2 kB/s eta 0:07:09
   -- ------------------------------------ 26.5/375.7 MB 798.1 kB/s eta 0:07:18
   -- ------------------------------------ 26.7/375.7 MB 797.7 kB/s eta 0:07:18
   -- ------------------------------------ 26.7/375.7 MB 797.7 kB/s eta 0:07:18
   -- ------------------------------------ 27.0/375.7 MB 793.9 kB/s eta 0:07:20
   -- ------------------------------------ 27.0/375.7 MB 793.9 kB/s eta 0:07:20
   -- ------------------------------------ 27.3/375.7 MB 774.2 kB/s eta 0:07:31
   -- ------------------------------------ 27.3/375.7 MB 774.2 kB/s eta 0:07:31
   -- ------------------------------------ 27.5/375.7 MB 765.8 kB/s eta 0:07:35
   -- ------------------------------------ 27.5/375.7 MB 765.8 kB/s eta 0:07:35
   -- ------------------------------------ 27.8/375.7 MB 762.2 kB/s eta 0:07:37
   -- ------------------------------------ 27.8/375.7 MB 762.2 kB/s eta 0:07:37
   -- ------------------------------------ 28.0/375.7 MB 754.6 kB/s eta 0:07:41
   -- ------------------------------------ 28.3/375.7 MB 746.6 kB/s eta 0:07:46
   -- ------------------------------------ 28.3/375.7 MB 746.6 kB/s eta 0:07:46
   -- ------------------------------------ 28.6/375.7 MB 748.2 kB/s eta 0:07:44
   -- ------------------------------------ 28.8/375.7 MB 737.8 kB/s eta 0:07:51
   -- ------------------------------------ 28.8/375.7 MB 737.8 kB/s eta 0:07:51
   --- ----------------------------------- 29.1/375.7 MB 734.8 kB/s eta 0:07:52
   --- ----------------------------------- 29.4/375.7 MB 730.6 kB/s eta 0:07:55
   --- ----------------------------------- 29.4/375.7 MB 730.6 kB/s eta 0:07:55
   --- ----------------------------------- 29.6/375.7 MB 728.7 kB/s eta 0:07:55
   --- ----------------------------------- 29.6/375.7 MB 728.7 kB/s eta 0:07:55
   --- ----------------------------------- 29.9/375.7 MB 725.3 kB/s eta 0:07:57
   --- ----------------------------------- 30.1/375.7 MB 720.7 kB/s eta 0:08:00
   --- ----------------------------------- 30.1/375.7 MB 720.7 kB/s eta 0:08:00
   --- ----------------------------------- 30.4/375.7 MB 717.7 kB/s eta 0:08:02
   --- ----------------------------------- 30.4/375.7 MB 717.7 kB/s eta 0:08:02
   --- ----------------------------------- 30.7/375.7 MB 709.6 kB/s eta 0:08:07
   --- ----------------------------------- 30.9/375.7 MB 703.8 kB/s eta 0:08:10
   --- ----------------------------------- 30.9/375.7 MB 703.8 kB/s eta 0:08:10
   --- ----------------------------------- 31.2/375.7 MB 694.3 kB/s eta 0:08:17
   --- ----------------------------------- 31.2/375.7 MB 694.3 kB/s eta 0:08:17

In [48]:
import tensorflow as tf

In [49]:
from tensorflow.keras.models import Sequential

In [50]:
from tensorflow.keras.layers import Dense