In [1]:
# Film tavsiyesi - Popularity Based Matrix Facto

In [2]:
import pandas as pd

In [3]:
rating = pd.read_csv('ml-100k/ml-100k/u.data' , sep = '\t', header = None , names = ['user_id', 'movie_id' , 'rating'] , usecols=range(3))
# veriler virgülle ayrılmadığı için sep ile ayırma ifadesini seçtik , başlıkta eklemedikleri için header none seçtik , sütun isimlerini verdik, kolonları ayarladık usecol ile

In [4]:
rating.head()

   user_id  movie_id  rating
0      196       242       3
1      186       302       3
2       22       377       1
3      244        51       2
4      166       346       1

In [5]:
movies = pd.read_csv('ml-100k/ml-100k/u.item' , encoding =' iso-8859-1', sep = '|' , header = None , names = ['movie_id' , 'title'], usecols = range(2))

In [6]:
movies.head()

   movie_id              title
0         1   Toy Story (1995)
1         2   GoldenEye (1995)
2         3  Four Rooms (1995)
3         4  Get Shorty (1995)
4         5     Copycat (1995)

In [7]:
user = pd.read_csv('ml-100k/ml-100k/u.user' , sep = '|' , header = None , names = ['name_id' , 'Age' , 'Gender' ,'Profession ', 'Zipcode' ])

In [8]:
user

     name_id  Age Gender    Profession  Zipcode
0          1   24      M     technician   85711
1          2   53      F          other   94043
2          3   23      M         writer   32067
3          4   24      M     technician   43537
4          5   33      F          other   15213
..       ...  ...    ...            ...     ...
938      939   26      F        student   33319
939      940   32      M  administrator   02215
940      941   20      M        student   97229
941      942   48      F      librarian   78209
942      943   22      M        student   77841

[943 rows x 5 columns]

In [9]:
# tabloları birleştircez

In [10]:
rating = pd.merge(movies , rating)

In [11]:
rating.head()

   movie_id             title  user_id  rating
0         1  Toy Story (1995)      308       4
1         1  Toy Story (1995)      287       5
2         1  Toy Story (1995)      148       4
3         1  Toy Story (1995)      280       4
4         1  Toy Story (1995)       66       3

In [12]:
rating.title.value_counts()

title
Star Wars (1977)                        583
Contact (1997)                          509
Fargo (1996)                            508
Return of the Jedi (1983)               507
Liar Liar (1997)                        485
                                       ...
Invitation, The (Zaproszenie) (1986)      1
Symphonie pastorale, La (1946)            1
Nothing Personal (1995)                   1
Ripe (1996)                               1
Brother's Kiss, A (1997)                  1
Name: count, Length: 1664, dtype: int64