# This is a  Regression & Classification project

#### A DATA SCIENCE APPROACH TO PROFILING ONLINE DATERS ACCORDING TO AGE & GENERATION

##### 1 - Can your dating profile predict your age? Regression Deep Learning

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('profiles.csv')

C:\Users\USER\AppData\Local\Temp\ipykernel_4700\2923526071.py:1: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,19,20,21,22,23,24,25,26,27,28,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('profiles.csv')

In [3]:
df.head()

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22.0,a little extra,strictly anything,socially,never,working on college/university,about me:<br />\n<br />\ni would love to think...,currently working as an international agent fo...,making people laugh.<br />\nranting about a go...,"the way i look. i am a six foot half asian, ha...",...,"south san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,35.0,average,mostly other,often,sometimes,working on space camp,i am a chef: this is what that means.<br />\n1...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,NaN,...,"oakland, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,38.0,thin,anything,socially,NaN,graduated from masters program,"i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,...,"san francisco, california",NaN,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,23.0,thin,vegetarian,socially,NaN,working on college/university,i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,...,"berkeley, california",doesn&rsquo;t want kids,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,29.0,athletic,NaN,socially,never,graduated from college/university,hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at:<br />\nhttp://bag...,i smile a lot and my inquisitive nature,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single

In [4]:
df.shape

(60552, 31)

In [5]:
df

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22.0,a little extra,strictly anything,socially,never,working on college/university,about me:<br />\n<br />\ni would love to think...,currently working as an international agent fo...,making people laugh.<br />\nranting about a go...,"the way i look. i am a six foot half asian, ha...",...,"south san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,35.0,average,mostly other,often,sometimes,working on space camp,i am a chef: this is what that means.<br />\n1...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,NaN,...,"oakland, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,38.0,thin,anything,socially,NaN,graduated from masters program,"i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,...,"san francisco, california",NaN,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,23.0,thin,vegetarian,socially,NaN,working on college/university,i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,...,"berkeley, california",doesn&rsquo;t want kids,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,29.0,athletic,NaN,socially,never,graduated from college/university,hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at:<br />\nhttp://bag...,i smile a lot and my inquisitive nature,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60551,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.isnull().sum()

age            51038
body_type      51886
diet           54791
drinks         51540
drugs          53337
education      52093
essay0         51885
essay1         52205
essay2         52503
essay3         52862
essay4         52673
essay5         52738
essay6         53200
essay7         52999
essay8         54191
essay9         52998
ethnicity      51987
height         51038
income         51038
job            52369
last_online    51038
location       51038
offspring      56666
orientation    51038
pets           54200
religion       54291
sex            51038
sign           52776
smokes         51956
speaks         51044
status         51038
dtype: int64

In [29]:
df.head(9515)

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22.0,a little extra,strictly anything,socially,never,working on college/university,about me:<br />\n<br />\ni would love to think...,currently working as an international agent fo...,making people laugh.<br />\nranting about a go...,"the way i look. i am a six foot half asian, ha...",...,"south san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,35.0,average,mostly other,often,sometimes,working on space camp,i am a chef: this is what that means.<br />\n1...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,NaN,...,"oakland, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,38.0,thin,anything,socially,NaN,graduated from masters program,"i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,...,"san francisco, california",NaN,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,23.0,thin,vegetarian,socially,NaN,working on college/university,i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,...,"berkeley, california",doesn&rsquo;t want kids,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,29.0,athletic,NaN,socially,never,graduated from college/university,hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at:<br />\nhttp://bag...,i smile a lot and my inquisitive nature,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9510,31.0,athletic,mostly anything,socially,sometimes,NaN,i work in the beauty salon as a hairstylist fo...,making your hair look beautiful.,i'm a hairstylist and love making hair look be...,i am different.,...,"san francisco, california",NaN,gay,NaN,atheism,m,scorpio but it doesn&rsquo;t matter,sometimes,english,single
9511,34.0,average,NaN,socially,NaN,dropped out of college/university,"33 year old, hiv +,versatile gwm, bearish type...",i've just recently moved to beautiful san fran...,"buying ""crap"" at random places and then sellin...",i usually go unnoticed.......,...,"san francisco, california",doesn&rsquo;t want kids,gay,likes dogs and has cats,atheism and laughing about it,m,leo and it&rsquo;s fun to think about,when drinking,english (fluently),single
9512,29.0,athletic,anything,rarely,never,two-year college,NaN,NaN,NaN,NaN,...,"san francisco, california","doesn&rsquo;t have kids, and doesn&rsquo;t wan...",gay,likes dogs and has cats,NaN,m,aries,no,"english (fluently), french (okay), swedish (po...",single
9513,49.0,overweight,NaN,rarely,never,graduated from college/university,NaN,NaN,NaN,NaN,...,"castro valley, california",NaN,straight,likes dogs and likes cats,NaN,f,pisces and it&rsquo;s fun to think about,no,english,single
9514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
 df.head(9515).isna().sum(axis=1)

0        0
1        4
2        6
3        5
4        8
        ..
9510     5
9511     2
9512    12
9513    11
9514    31
Length: 9515, dtype: int64

In [38]:
df = df.iloc[:9514]

In [39]:
df.shape

(9514, 31)

In [40]:
df.tail(50)

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
9464,34.0,average,mostly vegetarian,NaN,NaN,graduated from law school,"i like to travel, ride my bike, lay in the par...",working (a lot); in the midst of foreign servi...,throwing a kick ass bbq; making awkward situat...,that i am anxious. and my eyes.,...,"san francisco, california",NaN,straight,likes dogs and has cats,buddhism,f,taurus,NaN,"english, spanish (poorly)",single
9465,19.0,average,vegan,often,often,working on college/university,"im $0ph1$t1cated, b1tch.<br />\n<br />\nyea......",well according to this...<br />\nhttp://www.yo...,NaN,http://www.youtube.com/watch?v=wangqlo2afw<br ...,...,"alameda, california",doesn&rsquo;t have kids,straight,has cats,agnosticism and laughing about it,f,gemini and it&rsquo;s fun to think about,when drinking,"english (okay), spanish (poorly)",single
9466,27.0,average,anything,socially,NaN,graduated from masters program,summation is difficult for an overly- analytic...,depends on the day you ask me but generally re...,"nerdy science stuff ;-), shooting the breeze w...",the lovely teeth my orthodontist perfected...t...,...,"san francisco, california",doesn&rsquo;t have kids,straight,likes dogs and likes cats,agnosticism but not too serious about it,f,gemini but it doesn&rsquo;t matter,no,"english (fluently), spanish (okay)",single
9467,25.0,thin,NaN,often,NaN,working on college/university,"hey guys, i'm active on cupid again after a lo...",i stand at tables of seated people and tell th...,"making friends laugh, mashed potatoes, fake ou...",definitely my hunchback. (note: i had original...,...,"san francisco, california",NaN,gay,has cats,atheism,m,leo but it doesn&rsquo;t matter,when drinking,english,single
9468,23.0,athletic,NaN,rarely,never,working on college/university,NaN,working<br />\nattending college<br />\nexplor...,ditching people.<br />\npretending to enjoy ba...,??? idk,...,"richmond, california",NaN,straight,likes dogs,NaN,m,libra,NaN,"english, spanish (poorly)",single
9469,20.0,skinny,NaN,often,never,NaN,ask n i will tell :),NaN,NaN,NaN,...,"san francisco, california",NaN,straight,NaN,christianity,m,aries and it&rsquo;s fun to think about,no,english,single
9470,26.0,average,strictly vegetarian,often,sometimes,working on college/university,in 2009 i read about human parasites...all yea...,"i have pretty awful social anxiety, so crowded...","1) i can whistle with my throat, to this day i...","i'm human, i'm possibly on-edge, i have a face...",...,"oakland, california","doesn&rsquo;t have kids, and doesn&rsquo;t wan...",straight,likes dogs and likes cats,atheism but not too serious about it,m,capricorn but it doesn&rsquo;t matter,no,english (fluently),single
9471,19.0,average,mostly anything,socially,never,working on college/university,my roommate sucks and likes to put random crap...,"school, school, school, and friends...and school.",being modest? so i have no idea.,fuck if i know,...,"san francisco, california",NaN,gay,likes dogs and has cats,agnosticism,f,sagittarius but it doesn&rsquo;t matter,no,english (fluently),single
9472,25.0,average,NaN,rarely,never,graduated from college/university,born and raised in the sf bay area. but i stil...,big picture: trying to figure it out; right no...,"finding beauty in small details, brainstorming...",my big brown eyes.,...,"daly city, california",NaN,straight,NaN,agnosticism,f,leo,no,english,single
9473,28.0,NaN,NaN,socially,never,NaN,NaN,NaN,NaN,NaN,...,"berkeley, california",NaN,straight,NaN,NaN,f,pisces,no,english,single
9474,35.0,average,mostly anything,socially,NaN,graduated from masters program,NaN,so what i do with my life... i work in art edu...,making things.<br />\nfiguring shit out.<br />...,"people often think they already know me, or th...",...,"san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,NaN,f,capricorn and it&rsquo;s fun to think about,NaN,"english (fluently), french (poorly)",single
9475,68.0,athletic,anything,NaN,never,NaN,"hard body prof.affectionate,considerate--cycli...",investing &amp; playing,NaN,don't know,...,"walnut creek, california",NaN,straight,NaN,NaN,m,NaN,NaN,english,single
9476,30.0,fit,NaN,often,never,working on college/university,i am enigma. i have to write more because they...,"making the most of it, saving my days. http://...","anything and everything? cocky, no, just confi...",that i don't look full asian. and the cowlick ...,...,"san francisco, california",NaN,straight,NaN,agnosticism but not too serious about it,m,NaN,no,"english (fluently), chinese (fluently)",seeing someone
9477,52.0,thin,NaN,socially,never,graduated from college/university,i ponder the contradiction of these two things...,i love learning new things. it's what makes th...,"i'm not really good at all these things, but i...",i smile a lot,...,"mill valley, california",has a kid,straight,has dogs,christianity but not too serious about it,f,aries,no,"english (fluently), italian (poorly)",single
9478,40.0,fit,other,socially,never,graduated from masters program,"i'm originally from the east coast, have lived...","exploring inner and outer realms, dancing, yog...","physical and mental contortion, kissing, fitti...","that i'm grounded, open and that they feel at ...",...,"oakland, california",NaN,straight,likes dogs and likes cats,other and laughing about it,f,libra and it&rsquo;s fun to think about,no,"english, french (poorly)",single
9479,21.0,average,mostly anything,not at all,never,working on two-year college,i want to mold you not hold you bab its money ...,im getting money everyday saving it so i can b...,NaN,my eyes and how tall i am.,...,"hayward, california",doesn&rsquo;t have kids,straight,NaN,christianity and somewhat serious about it,m,pisces and it&rsquo;s fun to think about,yes,english,single
9480,51.0,fit,strictly anything,socially,NaN,graduated from college/university,"i have no stomach for ""conventional wisdom."" i...",creative and politically active work for a lab...,creating. guessing what time it is by looking ...,"i don't think it's always the first thing, but...",...,"oakland, california",NaN,straight,likes dogs and likes cats,other,m,leo and it&rsquo;s fun to think about,no,english,single
9481,30.0,a little extra,anything,socially,never,NaN,NaN,working hard to provide my kids everything i n...,making people laugh n have a good time.,not really sure but i get comments on my tatto...,...,"san leandro, california","has kids, but doesn&rsquo;t want more",straight,NaN,NaN,m,aquarius,yes,"english, spanish",single
9482,27.0,curvy,other,socially,sometimes,graduated from college/university,i'm a talker not a writer.... love to learn an...,i'm a freelance bookkeeper with an art history...,having conversations and listening.,"i get alot of ""you totally remind me of a frie...",...,"san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,other and laughing about it,f,gemini and it&rsquo;s fun to think about,no,"english, spanish (fluently)",single
9483,22.0,NaN,mostly anything,socially,never,graduated from college/university,i like to ski and play tennis. i've lived on t...,i just finished school back east (a nescac tha...,in interviews i always say i'm good at multita...,"i used to live in china, and i think over ther...",...,"san francisco, california",NaN,straight,NaN,NaN,f,capricorn,no,"english (fluently), chinese (fluently), hungar...",single
9484,28.0,average,NaN,socially,never,graduated from college/university,"new to sf, new to the online thing....just try...",just moved in san francisco in january for wor...,making people laugh.,NaN,...,"san francisco, california","doesn&rsquo;t have kids, but wants them",straight,likes dogs,christianity,f,NaN,no,english,single
9485,34.0,NaN,mostly vegan,socially,NaN,graduated from masters program,"i'm a botanist who loves travel, hiking, photo...",working to live not living to work.,NaN,NaN,...,"berkeley, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and has cats,atheism,f,virgo but it doesn&rsquo;t matter,no,english,single
9486,31.0,fit,anything,socially,NaN,graduated from college/university,NaN,currently i am working towards making my dream...,some fun facts:<br />\n-ping pong (yup i am a ...,i am tall and have beautiful eyes. also i've b...,...,"san francisco, california",NaN,straight,NaN,christianity,f,capricorn,no,"english (fluently), italian (okay)",single
9487,59.0,average,mostly anything,socially,never,graduated from college/university,having a bit of empty nest syndrome. trying to...,under construction,under construction,under construction,...,"albany, california","has kids, but doesn&rsquo;t want more",gay,likes dogs and likes cats,agnosticism,m,gemini but it doesn&rsquo;t matter,no,english,single
9488,18.0,average,strictly anything,not at all,never,working on two-year college,self summary? how can i summarize a life that ...,"im enjoying every last waking moment of it, re...","anything to do with my hands. that, and making...","dude, you look amish... (i'm not, i just love ...",...,"san francisco, california",NaN,straight,likes dogs and has cats,atheism,m,pisces and it&rsquo;s fun to think about,no,english (fluently),single
9489,42.0,thin,NaN,socially,never,graduated from college/university,"a little bit about me: i am fun, energetic, ro...",i work in marketing at a high tech company. th...,i'm good at speaking languages and have 4 unde...,my eyes,...,"san francisco, california",has a kid,straight,likes cats,judaism but not too serious about it,f,pisces and it&rsquo;s fun to think about,no,"english (fluently), german (fluently), dutch (...",single
9490,24.0,average,mostly vegetarian,socially,NaN,graduated from college/university,"""i'm just an animal looking for a home.""","travelling, breathing, walking, running, laugh...","laughing, hanging, cartwheels, and rock, paper...",it's the either the fact that i talk louder th...,...,"san francisco, california",NaN,straight,NaN,atheism and laughing about it,f,leo and it&rsquo;s fun to think about,sometimes,english,single
9491,31.0,fit,mostly vegetarian,socially,NaN,graduated from masters program,i am a college lecturer who used to be a balle...,right now i am trying to find a permanent job ...,"teaching, dancing, and yoga",my smile!,...,"san francisco, california","doesn&rsquo;t have kids, but wants them",straight,likes dogs and likes cats,other but not too serious about it,f,aquarius and it&rsquo;s fun to think about,NaN,english (fluently),single
9492,20.0,used up,mostly anything,socially,NaN,working on two-year college,at the moment i cant summarize myself i'll try...,"trying to figure it all out, oh and im really ...",going off topic for no reason. oh and pointing...,im not sure i never ask....maybe i should star...,...,"san francisco, california",NaN,straight,has dogs and likes cats,christianity but not too serious about it,m,capricorn and it&rsquo;s fun to think about,sometimes,english (fluently),single
9493,34.0,average,NaN,often,never,graduated from college/university,i skittered into the bay area over a year ago ...,i'm a big nerd about what i love: my professio...,"remembering useless trivia, identifying typogr...",my glasses and curly hair? that's enough for a...,...,"oakland, california",NaN,straight,has dogs,NaN,f,cancer but it doesn&rsquo;t matter,no,"english (fluently), french (okay), spanish (po...",single
9494,28.0,fit,NaN,socially,never,graduated from college/university,i want to meet all walks of life and explore. ...,i graduated from san francisco state universit...,"writing poems and performing, although it has ...",my smile and postive energy. it has been said ...,...,"san francisco, california",NaN,straight,dislikes cats,christianity but not too serious about it,f,aquarius and it&rsquo;s fun to think about,no,english (fluently),single
9495,37.0,athletic,anything,often,NaN,NaN,i try to laugh as much as possible and hang ou...,been working in the restaurant/bar/nightlife s...,at not talking about myself.....this is torture,"i can be a little on the loud side, so you mig...",...,"san francisco, california",NaN,straight,NaN,NaN,m,scorpio but it doesn&rsquo;t matter,no,english,single
9496,24.0,average,NaN,socially,NaN,NaN,born and raised in san francisco. went to scho...,"trying to find a balance, and loving it.",listening and laughing.,my eyes.,...,"san francisco, california",doesn&rsquo;t have kids,straight,NaN,judaism but not too serious about it,f,taurus and it&rsquo;s fun to think about,NaN,english,single
9497,28.0,overweight,mostly vegetarian,often,never,graduated from college/university,"i hate talking about myself, so ask me something!","i am a hairdresser, and considering going back...","annoying people, telling bad puns, and cooking.","is my hair. it's red. and yes, i was born with...",...,"redwood city, california","doesn&rsquo;t have kids, but wants them",straight,dislikes dogs and has cats,atheism and very serious about it,f,aquarius and it&rsquo;s fun to think about,no,"english (fluently), c++ (poorly)",single
9498,30.0,athletic,strictly vegetarian,socially,never,NaN,i'm very curious about the current state of th...,graduate school.,"taking risks, trading assets.",NaN,...,"san francisco, california",NaN,straight,NaN,NaN,f,NaN,no,english,single
9499,24.0,NaN,vegetarian,socially,NaN,graduated from college/university,"im kind of a hippie from santa cruz, born n' r...",i just graduated so now i'm taking a year off ...,"being a total goofball &amp; clutz, making peo...","i'd like to think my eyes or smile, but what i...",...,"berkeley, california",NaN,straight,likes dogs,NaN,f,gemini,when drinking,english,single
9500,23.0,fit,mostly anything,NaN,NaN,graduated from college/university,well i am a want to be adventurer born and rai...,i am getting ready to leave the city again and...,hmmmm awkward i would describe myself as a jac...,first that i take photos cause i have a camera...,...,"san francisco, california",NaN,straight,likes dogs and likes cats,agnosticism and laughing about it,m,libra and it&rsquo;s fun to think about,NaN,"english (fluently), spanish, swedish",single
9501,28.0,NaN,NaN,socially,NaN,graduated from college/university,"**seeing someone, but happy for friends.** :)<...",finding the things that make me happy and hope...,"crafts, especially making costume accessories ...","i smile, a lot.<br />\n<br />\nmy hair changes...",...,"san francisco, california",NaN,straight,likes dogs and likes cats,atheism and laughing about it,f,aquarius and it&rsquo;s fun to think about,no,"english (fluently), spanish (okay)",seeing someone
9502,31.0,athletic,mostly anything,socially,NaN,graduated from ph.d program,i'm a happy person. life is goodat least that'...,"i just finished my phd, and am now teaching at...",i'm really good at making my friends laugh. i'...,my gnarly dreadlocks ... on clear display in m...,...,"berkeley, california",NaN,straight,NaN,catholicism and laughing about it,m,NaN,no,english,single
9503,34.0,average,mostly anything,socially,never,graduated from law school,i love being me and not trying to change you. ...,living it happily and in the most honest and f...,"cooking, persuading, and giving.",my smile and my glasses :),...,"alameda, california",has a kid,straight,has dogs,christianity but not too serious about it,f,leo and it&rsquo;s fun to think about,no,english,single
9504,36.0,fit,NaN,socially,never,graduated from college/university,summarize myself in this small space? not bloo...,living it.,"logic puzzles, word games, being a confidante,...","red hair, height, broad shoulders, and smile.",...,"menlo park, california",NaN,straight,likes cats,other but not too serious about it,m,pisces and it&rsquo;s fun to think about,no,english,single
9505,33.0,fit,mostly anything,socially,never,graduated from college/university,i am a graphic designer by trade and by heart....,compulsively shopping online.,being honest and making amazing cocktails.,soft hands. i kid you not. i could win awards ...,...,"san francisco, california",doesn&rsquo;t have kids,straight,has dogs,NaN,f,virgo,no,"english (fluently), spanish (okay)",single
9506,43.0,athletic,mostly vegetarian,socially,NaN,graduated from college/university,the theme that runs deepest in my life is spir...,i've been pretty focused on career for the las...,editing<br />\nlistening<br />\nbeing a free s...,my eyes.,...,"belvedere tiburon, california",doesn&rsquo;t have kids,straight,likes dogs and likes cats,other and somewhat serious about it,f,leo and it&rsquo;s fun to think about,no,"english (fluently), spanish (poorly)",single
9507,41.0,fit,NaN,socially,never,graduated from masters program,"i'm an idealist-realist, which means i have a ...","dedicated public servant, i run into burning b...",talking with strangers and getting them to tel...,thick almost porcupine like hair.,...,"mountain view, california",NaN,straight,NaN,agnosticism but not too serious about it,m,pisces but it doesn&rsquo;t matter,no,english,single
9508,62.0,average,NaN,socially,never,graduated from college/university,"i am a libra, who is looking for a honest rela...",i am enjoy my life and exploring other opportu...,i enjoy cooking and baking for friends and fam...,"i am easy going and warm, gentle and soft spoken.",...,"san francisco, california",has a kid,straight,has dogs and dislikes cats,catholicism but not too serious about it,f,libra and it matters a lot,no,english (fluently),single
9509,28.0,athletic,strictly anything,socially,never,working on med school,just a normal guy looking for someone around m...,working hard and studying. things are always f...,"i'm excellent with oncology, numbers and algor...",my eyes change color.<br />\n<br />\ni smirk a...,...,"san francisco, california","doesn&rsquo;t have kids, but wants them",straight,likes dogs and likes cats,christianity,m,aries and it&rsquo;s fun to think about,no,"english, spanish (okay)",single
9510,31.0,athletic,mostly anything,socially,sometimes,NaN,i work in the beauty salon as a hairstylist fo...,making your hair look beautiful.,i'm a hairstylist and love making hair look be...,i am different.,...,"san francisco, california",NaN,gay,NaN,atheism,m,scorpio but it doesn&rsquo;t matter,sometimes,english,single
9511,34.0,average,NaN,socially,NaN,dropped out of college/university,"33 year old, hiv +,versatile gwm, bearish type...",i've just recently moved to beautiful san fran...,"buying ""crap"" at random places and then sellin...",i usually go unnoticed.......,...,"san francisco, california",doesn&rsquo;t want kids,gay,likes dogs and has cats,atheism and laughing about it,m,leo and it&rsquo;s fun to think about,when drinking,english (fluently),single
9512,29.0,athletic,anything,rarely,never,two-year college,NaN,NaN,NaN,NaN,...,"san francisco, california","doesn&rsquo;t have kids, and doesn&rsquo;t wan...",gay,likes dogs and has cats,NaN,m,aries,no,"english (fluently), french (okay), swedish (po...",single
9513,49.0,overweight,NaN,rarely,never,graduated from college/university,NaN,NaN,NaN,NaN,...,"castro valley, california",NaN,straight,likes dogs and likes cats,NaN,f,pisces and it&rsquo;s fun to think about,no,english,single

In [41]:
 df.head(9515).isna().sum(axis=1)

0        0
1        4
2        6
3        5
4        8
        ..
9509     0
9510     5
9511     2
9512    12
9513    11
Length: 9514, dtype: int64

In [44]:
df.columns

Index(['age', 'body_type', 'diet', 'drinks', 'drugs', 'education', 'essay0',
       'essay1', 'essay2', 'essay3', 'essay4', 'essay5', 'essay6', 'essay7',
       'essay8', 'essay9', 'ethnicity', 'height', 'income', 'job',
       'last_online', 'location', 'offspring', 'orientation', 'pets',
       'religion', 'sex', 'sign', 'smokes', 'speaks', 'status'],
      dtype='object')

In [ ]:
df.drop(columns=['essay0', 'essay1'])