# This is a  Regression & Classification project

#### A DATA SCIENCE APPROACH TO PROFILING ONLINE DATERS ACCORDING TO AGE & GENERATION

##### 1 - Can your dating profile predict your age? Regression Deep Learning

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('profiles.csv')

C:\Users\USER\AppData\Local\Temp\ipykernel_12148\2923526071.py:1: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,19,20,21,22,23,24,25,26,27,28,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('profiles.csv')

In [3]:
df.head()

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22.0,a little extra,strictly anything,socially,never,working on college/university,about me:<br />\n<br />\ni would love to think...,currently working as an international agent fo...,making people laugh.<br />\nranting about a go...,"the way i look. i am a six foot half asian, ha...",...,"south san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,35.0,average,mostly other,often,sometimes,working on space camp,i am a chef: this is what that means.<br />\n1...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,NaN,...,"oakland, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,38.0,thin,anything,socially,NaN,graduated from masters program,"i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,...,"san francisco, california",NaN,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,23.0,thin,vegetarian,socially,NaN,working on college/university,i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,...,"berkeley, california",doesn&rsquo;t want kids,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,29.0,athletic,NaN,socially,never,graduated from college/university,hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at:<br />\nhttp://bag...,i smile a lot and my inquisitive nature,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single

In [4]:
df.shape

(60552, 31)

In [5]:
df

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22.0,a little extra,strictly anything,socially,never,working on college/university,about me:<br />\n<br />\ni would love to think...,currently working as an international agent fo...,making people laugh.<br />\nranting about a go...,"the way i look. i am a six foot half asian, ha...",...,"south san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,35.0,average,mostly other,often,sometimes,working on space camp,i am a chef: this is what that means.<br />\n1...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,NaN,...,"oakland, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,38.0,thin,anything,socially,NaN,graduated from masters program,"i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,...,"san francisco, california",NaN,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,23.0,thin,vegetarian,socially,NaN,working on college/university,i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,...,"berkeley, california",doesn&rsquo;t want kids,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,29.0,athletic,NaN,socially,never,graduated from college/university,hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at:<br />\nhttp://bag...,i smile a lot and my inquisitive nature,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60551,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.isnull().sum()

age            51038
body_type      51886
diet           54791
drinks         51540
drugs          53337
education      52093
essay0         51885
essay1         52205
essay2         52503
essay3         52862
essay4         52673
essay5         52738
essay6         53200
essay7         52999
essay8         54191
essay9         52998
ethnicity      51987
height         51038
income         51038
job            52369
last_online    51038
location       51038
offspring      56666
orientation    51038
pets           54200
religion       54291
sex            51038
sign           52776
smokes         51956
speaks         51044
status         51038
dtype: int64

In [7]:
df.head(9515)

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22.0,a little extra,strictly anything,socially,never,working on college/university,about me:<br />\n<br />\ni would love to think...,currently working as an international agent fo...,making people laugh.<br />\nranting about a go...,"the way i look. i am a six foot half asian, ha...",...,"south san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,35.0,average,mostly other,often,sometimes,working on space camp,i am a chef: this is what that means.<br />\n1...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,NaN,...,"oakland, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,38.0,thin,anything,socially,NaN,graduated from masters program,"i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,...,"san francisco, california",NaN,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,23.0,thin,vegetarian,socially,NaN,working on college/university,i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,...,"berkeley, california",doesn&rsquo;t want kids,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,29.0,athletic,NaN,socially,never,graduated from college/university,hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at:<br />\nhttp://bag...,i smile a lot and my inquisitive nature,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9510,31.0,athletic,mostly anything,socially,sometimes,NaN,i work in the beauty salon as a hairstylist fo...,making your hair look beautiful.,i'm a hairstylist and love making hair look be...,i am different.,...,"san francisco, california",NaN,gay,NaN,atheism,m,scorpio but it doesn&rsquo;t matter,sometimes,english,single
9511,34.0,average,NaN,socially,NaN,dropped out of college/university,"33 year old, hiv +,versatile gwm, bearish type...",i've just recently moved to beautiful san fran...,"buying ""crap"" at random places and then sellin...",i usually go unnoticed.......,...,"san francisco, california",doesn&rsquo;t want kids,gay,likes dogs and has cats,atheism and laughing about it,m,leo and it&rsquo;s fun to think about,when drinking,english (fluently),single
9512,29.0,athletic,anything,rarely,never,two-year college,NaN,NaN,NaN,NaN,...,"san francisco, california","doesn&rsquo;t have kids, and doesn&rsquo;t wan...",gay,likes dogs and has cats,NaN,m,aries,no,"english (fluently), french (okay), swedish (po...",single
9513,49.0,overweight,NaN,rarely,never,graduated from college/university,NaN,NaN,NaN,NaN,...,"castro valley, california",NaN,straight,likes dogs and likes cats,NaN,f,pisces and it&rsquo;s fun to think about,no,english,single
9514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
 df.head(9515).isna().sum(axis=1) # Bundan sonraki satirlar boş olduğu için silindi

0        0
1        4
2        6
3        5
4        8
        ..
9510     5
9511     2
9512    12
9513    11
9514    31
Length: 9515, dtype: int64

In [9]:
df = df.iloc[:9514]

In [10]:
df.shape

(9514, 31)

In [11]:
df.tail()

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
9509,28.0,athletic,strictly anything,socially,never,working on med school,just a normal guy looking for someone around m...,working hard and studying. things are always f...,"i'm excellent with oncology, numbers and algor...",my eyes change color.<br />\n<br />\ni smirk a...,...,"san francisco, california","doesn&rsquo;t have kids, but wants them",straight,likes dogs and likes cats,christianity,m,aries and it&rsquo;s fun to think about,no,"english, spanish (okay)",single
9510,31.0,athletic,mostly anything,socially,sometimes,NaN,i work in the beauty salon as a hairstylist fo...,making your hair look beautiful.,i'm a hairstylist and love making hair look be...,i am different.,...,"san francisco, california",NaN,gay,NaN,atheism,m,scorpio but it doesn&rsquo;t matter,sometimes,english,single
9511,34.0,average,NaN,socially,NaN,dropped out of college/university,"33 year old, hiv +,versatile gwm, bearish type...",i've just recently moved to beautiful san fran...,"buying ""crap"" at random places and then sellin...",i usually go unnoticed.......,...,"san francisco, california",doesn&rsquo;t want kids,gay,likes dogs and has cats,atheism and laughing about it,m,leo and it&rsquo;s fun to think about,when drinking,english (fluently),single
9512,29.0,athletic,anything,rarely,never,two-year college,NaN,NaN,NaN,NaN,...,"san francisco, california","doesn&rsquo;t have kids, and doesn&rsquo;t wan...",gay,likes dogs and has cats,NaN,m,aries,no,"english (fluently), french (okay), swedish (po...",single
9513,49.0,overweight,NaN,rarely,never,graduated from college/university,NaN,NaN,NaN,NaN,...,"castro valley, california",NaN,straight,likes dogs and likes cats,NaN,f,pisces and it&rsquo;s fun to think about,no,english,single

In [12]:
 df.head(9515).isna().sum(axis=1)

0        0
1        4
2        6
3        5
4        8
        ..
9509     0
9510     5
9511     2
9512    12
9513    11
Length: 9514, dtype: int64

In [13]:
df.columns

Index(['age', 'body_type', 'diet', 'drinks', 'drugs', 'education', 'essay0',
       'essay1', 'essay2', 'essay3', 'essay4', 'essay5', 'essay6', 'essay7',
       'essay8', 'essay9', 'ethnicity', 'height', 'income', 'job',
       'last_online', 'location', 'offspring', 'orientation', 'pets',
       'religion', 'sex', 'sign', 'smokes', 'speaks', 'status'],
      dtype='object')

In [14]:
df = df.drop(columns=['essay0', 'essay1', 'essay2', 'essay3', 'essay4', 'essay5', 'essay6', 'essay7', 'essay8', 'essay9'])

In [15]:
df.head()

,age,body_type,diet,drinks,drugs,education,ethnicity,height,income,job,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22.0,a little extra,strictly anything,socially,never,working on college/university,"asian, white",75.0,-1.0,transportation,...,"south san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,35.0,average,mostly other,often,sometimes,working on space camp,white,70.0,80000.0,hospitality / travel,...,"oakland, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,38.0,thin,anything,socially,NaN,graduated from masters program,NaN,68.0,-1.0,NaN,...,"san francisco, california",NaN,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,23.0,thin,vegetarian,socially,NaN,working on college/university,white,71.0,20000.0,student,...,"berkeley, california",doesn&rsquo;t want kids,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,29.0,athletic,NaN,socially,never,graduated from college/university,"asian, black, other",66.0,-1.0,artistic / musical / writer,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single

In [16]:
## Body_type regulation

In [17]:
df['body_type'].value_counts()

body_type
average           2274
fit               2040
athletic          1888
thin               740
curvy              626
a little extra     430
skinny             269
full figured       181
overweight          69
jacked              64
used up             47
rather not say      38
Name: count, dtype: int64

In [18]:
skinnystatus={"average":"fit",     
              "fit":"fit",
              "athletic":"fit",
              "thin":"fit",
              "curvy":"curvy",
              "a little extra":"curvy",
              "skinny":"fit",
              "full figured":"curvy",
              "overweight":"bad",
              "jacked":"bad",
              "used up":"bad",
              "rather not say":"curvy"
             }
df["body_type"] = df["body_type"].map(skinnystatus)      
# https://www.kaggle.com/code/suhedabirben/three-generations-seeking-romance-regression-class/notebook bu çözümden örnek alındı.

In [19]:
df['body_type'].value_counts()

body_type
fit      7211
curvy    1275
bad       180
Name: count, dtype: int64

In [20]:
df.dtypes

age            float64
body_type       object
diet            object
drinks          object
drugs           object
education       object
ethnicity       object
height         float64
income         float64
job             object
last_online     object
location        object
offspring       object
orientation     object
pets            object
religion        object
sex             object
sign            object
smokes          object
speaks          object
status          object
dtype: object

In [21]:
df['diet'].value_counts()

diet
mostly anything        2621
anything               1067
strictly anything       835
mostly vegetarian       568
mostly other            154
strictly vegetarian     135
vegetarian              111
strictly other           64
mostly vegan             52
other                    52
strictly vegan           40
vegan                    28
mostly halal             13
mostly kosher            12
strictly halal            4
strictly kosher           2
kosher                    2
halal                     1
Name: count, dtype: int64

In [22]:
dietstatus = {
        "mostly anything":"anything",
        "strictly anything":"anything",
        "mostly vegetarian" : "vegetarian",
        "strictly other": "other",
        "mostly vegan": "vegan",
        "strictly vegan ": "vegan",
        "mostly halal" : "other",
        "mostly kosher": "other",
        "strictly halal": "other",
        "strictly kosher": "other",
        "kosher" : "other",
        "halal" : "other"
}

In [23]:
df['diet'] = df['diet'].map(dietstatus)

In [24]:
df['diet'].value_counts()

diet
anything      3456
vegetarian     568
other           98
vegan           52
Name: count, dtype: int64

In [25]:
df.columns

Index(['age', 'body_type', 'diet', 'drinks', 'drugs', 'education', 'ethnicity',
       'height', 'income', 'job', 'last_online', 'location', 'offspring',
       'orientation', 'pets', 'religion', 'sex', 'sign', 'smokes', 'speaks',
       'status'],
      dtype='object')

In [26]:
df['drinks'].value_counts()

drinks
socially       6679
rarely          911
often           809
not at all      509
very often       54
desperately      50
Name: count, dtype: int64

In [27]:
df['drugs'].value_counts()

drugs
never        5972
sometimes    1181
often          62
Name: count, dtype: int64

In [28]:
df['education'].value_counts()

education
graduated from college/university    3770
graduated from masters program       1402
working on college/university         969
working on masters program            251
graduated from two-year college       245
graduated from high school            205
graduated from ph.d program           203
graduated from law school             177
working on two-year college           159
working on ph.d program               159
dropped out of college/university     149
college/university                    134
graduated from space camp             104
dropped out of space camp              87
working on space camp                  73
graduated from med school              73
working on law school                  55
two-year college                       43
working on med school                  41
dropped out of two-year college        34
masters program                        21
working on high school                 20
dropped out of ph.d program            19
dropped out of masters program         16
dropped out of high school             13
high school                            13
space camp                             10
ph.d program                            5
law school                              4
dropped out of law school               3
dropped out of med school               2
Name: count, dtype: int64

In [29]:
# önce durumları normalize et
df["education"] = df["education"].replace({
    "working on": "student",
    "graduated from": "graduated",
    "dropped out of": "dropped"
}, regex=True)

In [30]:
# ilk kelimeyi al (student, graduated, dropped, vs.)
df["education"] = df["education"].str.split().str[0]

In [31]:
# eğitim seviyelerini toparla
df["education"] = df["education"].replace({
    "college/university": "student",
    "two-year": "student",
    "masters": "student",
    "ph.d": "graduated",
    "law": "graduated",
    "med": "graduated",
    "high": "graduated",
    "space": "student"
}, regex=True)

In [32]:
df["education"].value_counts()

education
graduated    6201
student      1935
dropped       323
Name: count, dtype: int64

In [33]:
# job ve etnik kökeni kategori olarak azaltamadığım için kaldırdım.
df.drop(["ethnicity","job"],axis=1,inplace=True)

In [34]:
df.shape

(9514, 19)

In [35]:
df["location"].value_counts()

location
san francisco, california    4835
oakland, california          1181
berkeley, california          768
san mateo, california         207
palo alto, california         170
                             ...
milwaukee, wisconsin            1
woodbridge, virginia            1
glencove, california            1
tiburon, california             1
madrid, spain                   1
Name: count, Length: 89, dtype: int64

In [36]:
df["location"] = df["location"].str.split(",").str[1].str.strip()

In [37]:
df["location"].value_counts()

location
california    9504
oregon           2
colorado         1
new york         1
arizona          1
hawaii           1
montana          1
wisconsin        1
virginia         1
spain            1
Name: count, dtype: int64

In [38]:
# genel lokasyona bakınca tamamına yakın california da yaşadığına karar verdiğim için location sütununu kaldırdım.

In [39]:
df.drop(["location"],axis=1,inplace=True)

In [40]:
df.columns

Index(['age', 'body_type', 'diet', 'drinks', 'drugs', 'education', 'height',
       'income', 'last_online', 'offspring', 'orientation', 'pets', 'religion',
       'sex', 'sign', 'smokes', 'speaks', 'status'],
      dtype='object')

In [41]:
df["offspring"].value_counts()

offspring
doesn&rsquo;t have kids                                1224
doesn&rsquo;t have kids, but might want them            620
doesn&rsquo;t have kids, but wants them                 578
doesn&rsquo;t want kids                                 454
has a kid                                               304
has kids                                                291
doesn&rsquo;t have kids, and doesn&rsquo;t want any     172
has kids, but doesn&rsquo;t want more                    68
has a kid, but doesn&rsquo;t want more                   41
has a kid, and might want more                           36
wants kids                                               29
might want kids                                          28
has kids, and might want more                            24
has a kid, and wants more                                12
has kids, and wants more                                  5
Name: count, dtype: int64

In [42]:
df["offspring"] = df["offspring"].replace({
    "doesn&rsquo;t have kids": 0,
    "doesn&rsquo;t have kids, but might want them": 0,
    "doesn&rsquo;t have kids, but wants them": 0,
    "doesn&rsquo;t want kids": 0,
    "doesn&rsquo;t have kids, and doesn&rsquo;t want any": 0,
    "wants kids": 0,
    "might want kids": 0,
    "has a kid": 1,
    "has kids": 1,
    "has kids, but doesn&rsquo;t want more": 1,
    "has a kid, but doesn&rsquo;t want more": 1,
    "has a kid, and might want more": 1,
    "has kids, and might want more": 1,
    "has a kid, and wants more": 1,
    "has kids, and wants more": 1
}, regex=False)

C:\Users\USER\AppData\Local\Temp\ipykernel_12148\4162091424.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["offspring"] = df["offspring"].replace({

In [43]:
df["offspring"] = df["offspring"].fillna(-1).astype(int)

In [44]:
df["offspring"].value_counts()

offspring
-1    5628
 0    3105
 1     781
Name: count, dtype: int64

In [45]:
df["religion"].value_counts()

religion
agnosticism                                   448
other                                         417
agnosticism but not too serious about it      400
agnosticism and laughing about it             386
catholicism but not too serious about it      367
atheism                                       363
atheism and laughing about it                 329
other and laughing about it                   325
christianity but not too serious about it     320
christianity                                  297
other but not too serious about it            243
judaism but not too serious about it          232
atheism but not too serious about it          200
catholicism                                   165
atheism and somewhat serious about it         138
christianity and somewhat serious about it    133
other and somewhat serious about it           122
catholicism and laughing about it             117
judaism and laughing about it                 113
agnosticism and somewhat serious about it     105
atheism and very serious about it             101
buddhism but not too serious about it          97
christianity and very serious about it         96
judaism                                        93
catholicism and somewhat serious about it      93
other and very serious about it                86
buddhism                                       72
christianity and laughing about it             59
buddhism and laughing about it                 55
buddhism and somewhat serious about it         52
judaism and somewhat serious about it          49
agnosticism and very serious about it          42
hinduism but not too serious about it          40
catholicism and very serious about it          20
hinduism                                       17
buddhism and very serious about it             12
islam                                          12
islam but not too serious about it             12
hinduism and somewhat serious about it         11
hinduism and laughing about it                  9
hinduism and very serious about it              5
islam and very serious about it                 3
judaism and very serious about it               3
islam and laughing about it                     1
islam and somewhat serious about it             1
Name: count, dtype: int64

In [46]:
df["religion"]=df["religion"].str.split().str[0]

In [47]:
df.head()

,age,body_type,diet,drinks,drugs,education,height,income,last_online,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22.0,curvy,anything,socially,never,student,75.0,-1.0,2012-06-28-20-30,0,straight,likes dogs and likes cats,agnosticism,m,gemini,sometimes,english,single
1,35.0,fit,NaN,often,sometimes,student,70.0,80000.0,2012-06-29-21-41,0,straight,likes dogs and likes cats,agnosticism,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,38.0,fit,NaN,socially,NaN,graduated,68.0,-1.0,2012-06-27-09-10,-1,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,23.0,fit,NaN,socially,NaN,student,71.0,20000.0,2012-06-28-14-22,0,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,29.0,fit,NaN,socially,never,graduated,66.0,-1.0,2012-06-27-21-26,-1,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single