# This is a  Regression & Classification project

#### A DATA SCIENCE APPROACH TO PROFILING ONLINE DATERS ACCORDING TO AGE & GENERATION

##### 1 - Can your dating profile predict your age? Regression Deep Learning

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('profiles.csv')

C:\Users\USER\AppData\Local\Temp\ipykernel_22944\2923526071.py:1: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,19,20,21,22,23,24,25,26,27,28,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('profiles.csv')

In [3]:
df.head()

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22.0,a little extra,strictly anything,socially,never,working on college/university,about me:<br />\n<br />\ni would love to think...,currently working as an international agent fo...,making people laugh.<br />\nranting about a go...,"the way i look. i am a six foot half asian, ha...",...,"south san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,35.0,average,mostly other,often,sometimes,working on space camp,i am a chef: this is what that means.<br />\n1...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,NaN,...,"oakland, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,38.0,thin,anything,socially,NaN,graduated from masters program,"i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,...,"san francisco, california",NaN,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,23.0,thin,vegetarian,socially,NaN,working on college/university,i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,...,"berkeley, california",doesn&rsquo;t want kids,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,29.0,athletic,NaN,socially,never,graduated from college/university,hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at:<br />\nhttp://bag...,i smile a lot and my inquisitive nature,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single

In [4]:
df.shape

(60552, 31)

In [5]:
df

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22.0,a little extra,strictly anything,socially,never,working on college/university,about me:<br />\n<br />\ni would love to think...,currently working as an international agent fo...,making people laugh.<br />\nranting about a go...,"the way i look. i am a six foot half asian, ha...",...,"south san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,35.0,average,mostly other,often,sometimes,working on space camp,i am a chef: this is what that means.<br />\n1...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,NaN,...,"oakland, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,38.0,thin,anything,socially,NaN,graduated from masters program,"i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,...,"san francisco, california",NaN,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,23.0,thin,vegetarian,socially,NaN,working on college/university,i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,...,"berkeley, california",doesn&rsquo;t want kids,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,29.0,athletic,NaN,socially,never,graduated from college/university,hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at:<br />\nhttp://bag...,i smile a lot and my inquisitive nature,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60551,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.isnull().sum()

age            51038
body_type      51886
diet           54791
drinks         51540
drugs          53337
education      52093
essay0         51885
essay1         52205
essay2         52503
essay3         52862
essay4         52673
essay5         52738
essay6         53200
essay7         52999
essay8         54191
essay9         52998
ethnicity      51987
height         51038
income         51038
job            52369
last_online    51038
location       51038
offspring      56666
orientation    51038
pets           54200
religion       54291
sex            51038
sign           52776
smokes         51956
speaks         51044
status         51038
dtype: int64

In [7]:
df.head(9515)

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22.0,a little extra,strictly anything,socially,never,working on college/university,about me:<br />\n<br />\ni would love to think...,currently working as an international agent fo...,making people laugh.<br />\nranting about a go...,"the way i look. i am a six foot half asian, ha...",...,"south san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,35.0,average,mostly other,often,sometimes,working on space camp,i am a chef: this is what that means.<br />\n1...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,NaN,...,"oakland, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,38.0,thin,anything,socially,NaN,graduated from masters program,"i'm not ashamed of much, but writing public te...","i make nerdy software for musicians, artists, ...",improvising in different contexts. alternating...,my large jaw and large glasses are the physica...,...,"san francisco, california",NaN,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,23.0,thin,vegetarian,socially,NaN,working on college/university,i work in a library and go to school. . .,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,...,"berkeley, california",doesn&rsquo;t want kids,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,29.0,athletic,NaN,socially,never,graduated from college/university,hey how's it going? currently vague on the pro...,work work work work + play,creating imagery to look at:<br />\nhttp://bag...,i smile a lot and my inquisitive nature,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9510,31.0,athletic,mostly anything,socially,sometimes,NaN,i work in the beauty salon as a hairstylist fo...,making your hair look beautiful.,i'm a hairstylist and love making hair look be...,i am different.,...,"san francisco, california",NaN,gay,NaN,atheism,m,scorpio but it doesn&rsquo;t matter,sometimes,english,single
9511,34.0,average,NaN,socially,NaN,dropped out of college/university,"33 year old, hiv +,versatile gwm, bearish type...",i've just recently moved to beautiful san fran...,"buying ""crap"" at random places and then sellin...",i usually go unnoticed.......,...,"san francisco, california",doesn&rsquo;t want kids,gay,likes dogs and has cats,atheism and laughing about it,m,leo and it&rsquo;s fun to think about,when drinking,english (fluently),single
9512,29.0,athletic,anything,rarely,never,two-year college,NaN,NaN,NaN,NaN,...,"san francisco, california","doesn&rsquo;t have kids, and doesn&rsquo;t wan...",gay,likes dogs and has cats,NaN,m,aries,no,"english (fluently), french (okay), swedish (po...",single
9513,49.0,overweight,NaN,rarely,never,graduated from college/university,NaN,NaN,NaN,NaN,...,"castro valley, california",NaN,straight,likes dogs and likes cats,NaN,f,pisces and it&rsquo;s fun to think about,no,english,single
9514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
 df.head(9515).isna().sum(axis=1) # Bundan sonraki satirlar boş olduğu için silindi

0        0
1        4
2        6
3        5
4        8
        ..
9510     5
9511     2
9512    12
9513    11
9514    31
Length: 9515, dtype: int64

In [9]:
df = df.iloc[:9514]

In [10]:
df.shape

(9514, 31)

In [11]:
df.tail()

,age,body_type,diet,drinks,drugs,education,essay0,essay1,essay2,essay3,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
9509,28.0,athletic,strictly anything,socially,never,working on med school,just a normal guy looking for someone around m...,working hard and studying. things are always f...,"i'm excellent with oncology, numbers and algor...",my eyes change color.<br />\n<br />\ni smirk a...,...,"san francisco, california","doesn&rsquo;t have kids, but wants them",straight,likes dogs and likes cats,christianity,m,aries and it&rsquo;s fun to think about,no,"english, spanish (okay)",single
9510,31.0,athletic,mostly anything,socially,sometimes,NaN,i work in the beauty salon as a hairstylist fo...,making your hair look beautiful.,i'm a hairstylist and love making hair look be...,i am different.,...,"san francisco, california",NaN,gay,NaN,atheism,m,scorpio but it doesn&rsquo;t matter,sometimes,english,single
9511,34.0,average,NaN,socially,NaN,dropped out of college/university,"33 year old, hiv +,versatile gwm, bearish type...",i've just recently moved to beautiful san fran...,"buying ""crap"" at random places and then sellin...",i usually go unnoticed.......,...,"san francisco, california",doesn&rsquo;t want kids,gay,likes dogs and has cats,atheism and laughing about it,m,leo and it&rsquo;s fun to think about,when drinking,english (fluently),single
9512,29.0,athletic,anything,rarely,never,two-year college,NaN,NaN,NaN,NaN,...,"san francisco, california","doesn&rsquo;t have kids, and doesn&rsquo;t wan...",gay,likes dogs and has cats,NaN,m,aries,no,"english (fluently), french (okay), swedish (po...",single
9513,49.0,overweight,NaN,rarely,never,graduated from college/university,NaN,NaN,NaN,NaN,...,"castro valley, california",NaN,straight,likes dogs and likes cats,NaN,f,pisces and it&rsquo;s fun to think about,no,english,single

In [12]:
 df.head(9515).isna().sum(axis=1)

0        0
1        4
2        6
3        5
4        8
        ..
9509     0
9510     5
9511     2
9512    12
9513    11
Length: 9514, dtype: int64

In [13]:
df.columns

Index(['age', 'body_type', 'diet', 'drinks', 'drugs', 'education', 'essay0',
       'essay1', 'essay2', 'essay3', 'essay4', 'essay5', 'essay6', 'essay7',
       'essay8', 'essay9', 'ethnicity', 'height', 'income', 'job',
       'last_online', 'location', 'offspring', 'orientation', 'pets',
       'religion', 'sex', 'sign', 'smokes', 'speaks', 'status'],
      dtype='object')

In [14]:
df = df.drop(columns=['essay0', 'essay1', 'essay2', 'essay3', 'essay4', 'essay5', 'essay6', 'essay7', 'essay8', 'essay9'])

In [15]:
df.head()

,age,body_type,diet,drinks,drugs,education,ethnicity,height,income,job,...,location,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22.0,a little extra,strictly anything,socially,never,working on college/university,"asian, white",75.0,-1.0,transportation,...,"south san francisco, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,35.0,average,mostly other,often,sometimes,working on space camp,white,70.0,80000.0,hospitality / travel,...,"oakland, california","doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,38.0,thin,anything,socially,NaN,graduated from masters program,NaN,68.0,-1.0,NaN,...,"san francisco, california",NaN,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,23.0,thin,vegetarian,socially,NaN,working on college/university,white,71.0,20000.0,student,...,"berkeley, california",doesn&rsquo;t want kids,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,29.0,athletic,NaN,socially,never,graduated from college/university,"asian, black, other",66.0,-1.0,artistic / musical / writer,...,"san francisco, california",NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single

In [16]:
## Body_type regulation

In [17]:
df['body_type'].value_counts()

body_type
average           2274
fit               2040
athletic          1888
thin               740
curvy              626
a little extra     430
skinny             269
full figured       181
overweight          69
jacked              64
used up             47
rather not say      38
Name: count, dtype: int64

In [18]:
skinnystatus={"average":"fit",     
              "fit":"fit",
              "athletic":"fit",
              "thin":"fit",
              "curvy":"curvy",
              "a little extra":"curvy",
              "skinny":"fit",
              "full figured":"curvy",
              "overweight":"bad",
              "jacked":"bad",
              "used up":"bad",
              "rather not say":"curvy"
             }
df["body_type"] = df["body_type"].map(skinnystatus)      
# https://www.kaggle.com/code/suhedabirben/three-generations-seeking-romance-regression-class/notebook bu çözümden örnek alındı.

In [19]:
df['body_type'].value_counts()

body_type
fit      7211
curvy    1275
bad       180
Name: count, dtype: int64

In [20]:
df.dtypes

age            float64
body_type       object
diet            object
drinks          object
drugs           object
education       object
ethnicity       object
height         float64
income         float64
job             object
last_online     object
location        object
offspring       object
orientation     object
pets            object
religion        object
sex             object
sign            object
smokes          object
speaks          object
status          object
dtype: object

In [21]:
df['diet'].value_counts()

diet
mostly anything        2621
anything               1067
strictly anything       835
mostly vegetarian       568
mostly other            154
strictly vegetarian     135
vegetarian              111
strictly other           64
mostly vegan             52
other                    52
strictly vegan           40
vegan                    28
mostly halal             13
mostly kosher            12
strictly halal            4
strictly kosher           2
kosher                    2
halal                     1
Name: count, dtype: int64

In [22]:
dietstatus = {
        "mostly anything":"anything",
        "strictly anything":"anything",
        "mostly vegetarian" : "vegetarian",
        "strictly other": "other",
        "mostly vegan": "vegan",
        "strictly vegan ": "vegan",
        "mostly halal" : "other",
        "mostly kosher": "other",
        "strictly halal": "other",
        "strictly kosher": "other",
        "kosher" : "other",
        "halal" : "other"
}

In [23]:
df['diet'] = df['diet'].map(dietstatus)

In [24]:
df['diet'].value_counts()

diet
anything      3456
vegetarian     568
other           98
vegan           52
Name: count, dtype: int64

In [25]:
df.columns

Index(['age', 'body_type', 'diet', 'drinks', 'drugs', 'education', 'ethnicity',
       'height', 'income', 'job', 'last_online', 'location', 'offspring',
       'orientation', 'pets', 'religion', 'sex', 'sign', 'smokes', 'speaks',
       'status'],
      dtype='object')

In [26]:
df['drinks'].value_counts()

drinks
socially       6679
rarely          911
often           809
not at all      509
very often       54
desperately      50
Name: count, dtype: int64

In [27]:
df['drugs'].value_counts()

drugs
never        5972
sometimes    1181
often          62
Name: count, dtype: int64

In [28]:
df['education'].value_counts()

education
graduated from college/university    3770
graduated from masters program       1402
working on college/university         969
working on masters program            251
graduated from two-year college       245
graduated from high school            205
graduated from ph.d program           203
graduated from law school             177
working on two-year college           159
working on ph.d program               159
dropped out of college/university     149
college/university                    134
graduated from space camp             104
dropped out of space camp              87
working on space camp                  73
graduated from med school              73
working on law school                  55
two-year college                       43
working on med school                  41
dropped out of two-year college        34
masters program                        21
working on high school                 20
dropped out of ph.d program            19
dropped out of masters program         16
dropped out of high school             13
high school                            13
space camp                             10
ph.d program                            5
law school                              4
dropped out of law school               3
dropped out of med school               2
Name: count, dtype: int64

In [29]:
# önce durumları normalize et
df["education"] = df["education"].replace({
    "working on": "student",
    "graduated from": "graduated",
    "dropped out of": "dropped"
}, regex=True)

In [30]:
# ilk kelimeyi al (student, graduated, dropped, vs.)
df["education"] = df["education"].str.split().str[0]

In [31]:
# eğitim seviyelerini toparla
df["education"] = df["education"].replace({
    "college/university": "student",
    "two-year": "student",
    "masters": "student",
    "ph.d": "graduated",
    "law": "graduated",
    "med": "graduated",
    "high": "graduated",
    "space": "student"
}, regex=True)

In [32]:
df["education"].value_counts()

education
graduated    6201
student      1935
dropped       323
Name: count, dtype: int64

In [33]:
# job ve etnik kökeni kategori olarak azaltamadığım için kaldırdım.
df.drop(["ethnicity","job"],axis=1,inplace=True)

In [34]:
df.shape

(9514, 19)

In [35]:
df["location"].value_counts()

location
san francisco, california    4835
oakland, california          1181
berkeley, california          768
san mateo, california         207
palo alto, california         170
                             ...
milwaukee, wisconsin            1
woodbridge, virginia            1
glencove, california            1
tiburon, california             1
madrid, spain                   1
Name: count, Length: 89, dtype: int64

In [36]:
df["location"] = df["location"].str.split(",").str[1].str.strip()

In [37]:
df["location"].value_counts()

location
california    9504
oregon           2
colorado         1
new york         1
arizona          1
hawaii           1
montana          1
wisconsin        1
virginia         1
spain            1
Name: count, dtype: int64

In [38]:
# genel lokasyona bakınca tamamına yakın california da yaşadığına karar verdiğim için location sütununu kaldırdım.

In [39]:
df.drop(["location"],axis=1,inplace=True)

In [40]:
df.columns

Index(['age', 'body_type', 'diet', 'drinks', 'drugs', 'education', 'height',
       'income', 'last_online', 'offspring', 'orientation', 'pets', 'religion',
       'sex', 'sign', 'smokes', 'speaks', 'status'],
      dtype='object')

In [41]:
df["offspring"].value_counts()

offspring
doesn&rsquo;t have kids                                1224
doesn&rsquo;t have kids, but might want them            620
doesn&rsquo;t have kids, but wants them                 578
doesn&rsquo;t want kids                                 454
has a kid                                               304
has kids                                                291
doesn&rsquo;t have kids, and doesn&rsquo;t want any     172
has kids, but doesn&rsquo;t want more                    68
has a kid, but doesn&rsquo;t want more                   41
has a kid, and might want more                           36
wants kids                                               29
might want kids                                          28
has kids, and might want more                            24
has a kid, and wants more                                12
has kids, and wants more                                  5
Name: count, dtype: int64

In [42]:
df["offspring"] = df["offspring"].replace({
    "doesn&rsquo;t have kids": 0,
    "doesn&rsquo;t have kids, but might want them": 0,
    "doesn&rsquo;t have kids, but wants them": 0,
    "doesn&rsquo;t want kids": 0,
    "doesn&rsquo;t have kids, and doesn&rsquo;t want any": 0,
    "wants kids": 0,
    "might want kids": 0,
    "has a kid": 1,
    "has kids": 1,
    "has kids, but doesn&rsquo;t want more": 1,
    "has a kid, but doesn&rsquo;t want more": 1,
    "has a kid, and might want more": 1,
    "has kids, and might want more": 1,
    "has a kid, and wants more": 1,
    "has kids, and wants more": 1
}, regex=False)

C:\Users\USER\AppData\Local\Temp\ipykernel_22944\4162091424.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["offspring"] = df["offspring"].replace({

In [43]:
df["offspring"] = df["offspring"].fillna(-1).astype(int)

In [44]:
df["offspring"].value_counts()

offspring
-1    5628
 0    3105
 1     781
Name: count, dtype: int64

In [45]:
df["religion"].value_counts()

religion
agnosticism                                   448
other                                         417
agnosticism but not too serious about it      400
agnosticism and laughing about it             386
catholicism but not too serious about it      367
atheism                                       363
atheism and laughing about it                 329
other and laughing about it                   325
christianity but not too serious about it     320
christianity                                  297
other but not too serious about it            243
judaism but not too serious about it          232
atheism but not too serious about it          200
catholicism                                   165
atheism and somewhat serious about it         138
christianity and somewhat serious about it    133
other and somewhat serious about it           122
catholicism and laughing about it             117
judaism and laughing about it                 113
agnosticism and somewhat serious about it     105
atheism and very serious about it             101
buddhism but not too serious about it          97
christianity and very serious about it         96
judaism                                        93
catholicism and somewhat serious about it      93
other and very serious about it                86
buddhism                                       72
christianity and laughing about it             59
buddhism and laughing about it                 55
buddhism and somewhat serious about it         52
judaism and somewhat serious about it          49
agnosticism and very serious about it          42
hinduism but not too serious about it          40
catholicism and very serious about it          20
hinduism                                       17
buddhism and very serious about it             12
islam                                          12
islam but not too serious about it             12
hinduism and somewhat serious about it         11
hinduism and laughing about it                  9
hinduism and very serious about it              5
islam and very serious about it                 3
judaism and very serious about it               3
islam and laughing about it                     1
islam and somewhat serious about it             1
Name: count, dtype: int64

In [46]:
df["religion"]=df["religion"].str.split().str[0] # ilk kelimeyi aldık

In [47]:
df["religion"].value_counts()

religion
agnosticism     1381
other           1193
atheism         1131
christianity     905
catholicism      762
judaism          490
buddhism         288
hinduism          82
islam             29
Name: count, dtype: int64

In [48]:
df.head()

,age,body_type,diet,drinks,drugs,education,height,income,last_online,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22.0,curvy,anything,socially,never,student,75.0,-1.0,2012-06-28-20-30,0,straight,likes dogs and likes cats,agnosticism,m,gemini,sometimes,english,single
1,35.0,fit,NaN,often,sometimes,student,70.0,80000.0,2012-06-29-21-41,0,straight,likes dogs and likes cats,agnosticism,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,38.0,fit,NaN,socially,NaN,graduated,68.0,-1.0,2012-06-27-09-10,-1,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,23.0,fit,NaN,socially,NaN,student,71.0,20000.0,2012-06-28-14-22,0,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,29.0,fit,NaN,socially,never,graduated,66.0,-1.0,2012-06-27-21-26,-1,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single

In [49]:
df["sign"].value_counts()

sign
leo and it&rsquo;s fun to think about            277
taurus and it&rsquo;s fun to think about         275
gemini and it&rsquo;s fun to think about         271
cancer and it&rsquo;s fun to think about         260
scorpio and it&rsquo;s fun to think about        258
libra and it&rsquo;s fun to think about          257
virgo and it&rsquo;s fun to think about          257
pisces and it&rsquo;s fun to think about         253
aries and it&rsquo;s fun to think about          252
aries but it doesn&rsquo;t matter                250
aquarius but it doesn&rsquo;t matter             250
sagittarius and it&rsquo;s fun to think about    242
leo but it doesn&rsquo;t matter                  239
virgo but it doesn&rsquo;t matter                236
gemini but it doesn&rsquo;t matter               235
aquarius and it&rsquo;s fun to think about       235
cancer but it doesn&rsquo;t matter               233
taurus but it doesn&rsquo;t matter               222
sagittarius but it doesn&rsquo;t matter          218
libra but it doesn&rsquo;t matter                216
capricorn and it&rsquo;s fun to think about      209
scorpio but it doesn&rsquo;t matter              201
pisces but it doesn&rsquo;t matter               192
capricorn but it doesn&rsquo;t matter            187
leo                                              181
cancer                                           175
aquarius                                         175
aries                                            172
pisces                                           169
libra                                            167
virgo                                            165
taurus                                           163
gemini                                           162
scorpio                                          158
sagittarius                                      136
capricorn                                        122
scorpio and it matters a lot                      15
aquarius and it matters a lot                     14
pisces and it matters a lot                       13
leo and it matters a lot                          10
capricorn and it matters a lot                    10
cancer and it matters a lot                        9
libra and it matters a lot                         8
sagittarius and it matters a lot                   8
gemini and it matters a lot                        8
aries and it matters a lot                         6
taurus and it matters a lot                        3
virgo and it matters a lot                         2
Name: count, dtype: int64

In [50]:
df["sign"]=df["sign"].str.split().str[0] # ilk kelimeyi aldık

In [51]:
df["sign"].value_counts()

sign
leo            707
aries          680
cancer         677
gemini         676
aquarius       674
taurus         663
virgo          660
libra          648
scorpio        632
pisces         627
sagittarius    604
capricorn      528
Name: count, dtype: int64

In [52]:
df["speaks"].value_counts()

speaks
english                                                                    3415
english (fluently)                                                         1106
english (fluently), spanish (okay)                                          322
english (fluently), spanish (poorly)                                        321
english (fluently), spanish (fluently)                                      195
                                                                           ...
english (fluently), c++ (okay), latin (poorly)                                1
english (fluently), arabic (poorly), french (okay), german (okay)             1
english (fluently), french (okay), latin (poorly), c++ (okay)                 1
english, spanish, arabic, swahili                                             1
english (fluently), french (fluently), german (okay), arabic (fluently)       1
Name: count, Length: 1794, dtype: int64

In [53]:
df["number_of_fluent_languages"]=df.speaks.str.count("fluently")
df["number_of_fluent_languages"].replace(0,1,regex=True,inplace=True)
df["number_of_poorly_languages"]=df.speaks.str.count("poorly")
df.drop("speaks",axis=1,inplace=True)
# https://www.kaggle.com/code/suhedabirben/three-generations-seeking-romance-regression-class/notebook bu çözümden alındı.

C:\Users\USER\AppData\Local\Temp\ipykernel_22944\1887541453.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["number_of_fluent_languages"].replace(0,1,regex=True,inplace=True)

In [54]:
df.head()

,age,body_type,diet,drinks,drugs,education,height,income,last_online,offspring,orientation,pets,religion,sex,sign,smokes,status,number_of_fluent_languages,number_of_poorly_languages
0,22.0,curvy,anything,socially,never,student,75.0,-1.0,2012-06-28-20-30,0,straight,likes dogs and likes cats,agnosticism,m,gemini,sometimes,single,1.0,0.0
1,35.0,fit,NaN,often,sometimes,student,70.0,80000.0,2012-06-29-21-41,0,straight,likes dogs and likes cats,agnosticism,m,cancer,no,single,1.0,2.0
2,38.0,fit,NaN,socially,NaN,graduated,68.0,-1.0,2012-06-27-09-10,-1,straight,has cats,NaN,m,pisces,no,available,1.0,0.0
3,23.0,fit,NaN,socially,NaN,student,71.0,20000.0,2012-06-28-14-22,0,straight,likes cats,NaN,m,pisces,no,single,1.0,1.0
4,29.0,fit,NaN,socially,never,graduated,66.0,-1.0,2012-06-27-21-26,-1,straight,likes dogs and likes cats,NaN,m,aquarius,no,single,1.0,0.0

In [55]:
df["last_online"].value_counts()

last_online
2012-06-29-22-56    15
2012-06-29-22-35    11
2012-06-29-22-58    11
2012-06-29-22-33    11
2012-06-29-23-43    10
                    ..
2012-06-25-00-49     1
2012-06-26-20-40     1
2012-06-29-16-08     1
2012-06-13-16-06     1
2012-05-28-21-28     1
Name: count, Length: 6763, dtype: int64

In [56]:
df["last_online_year"]=2025-(df['last_online'].str[:4]).astype(int)
df["last_online_month"]=(df['last_online'].str[5:7]).astype(int)
df.drop('last_online',axis=1)

,age,body_type,diet,drinks,drugs,education,height,income,offspring,orientation,pets,religion,sex,sign,smokes,status,number_of_fluent_languages,number_of_poorly_languages,last_online_year,last_online_month
0,22.0,curvy,anything,socially,never,student,75.0,-1.0,0,straight,likes dogs and likes cats,agnosticism,m,gemini,sometimes,single,1.0,0.0,13,6
1,35.0,fit,NaN,often,sometimes,student,70.0,80000.0,0,straight,likes dogs and likes cats,agnosticism,m,cancer,no,single,1.0,2.0,13,6
2,38.0,fit,NaN,socially,NaN,graduated,68.0,-1.0,-1,straight,has cats,NaN,m,pisces,no,available,1.0,0.0,13,6
3,23.0,fit,NaN,socially,NaN,student,71.0,20000.0,0,straight,likes cats,NaN,m,pisces,no,single,1.0,1.0,13,6
4,29.0,fit,NaN,socially,never,graduated,66.0,-1.0,-1,straight,likes dogs and likes cats,NaN,m,aquarius,no,single,1.0,0.0,13,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9509,28.0,fit,anything,socially,never,student,73.0,60000.0,0,straight,likes dogs and likes cats,christianity,m,aries,no,single,1.0,0.0,13,6
9510,31.0,fit,anything,socially,sometimes,NaN,72.0,-1.0,-1,gay,NaN,atheism,m,scorpio,sometimes,single,1.0,0.0,13,4
9511,34.0,fit,NaN,socially,NaN,dropped,71.0,-1.0,0,gay,likes dogs and has cats,atheism,m,leo,when drinking,single,1.0,0.0,13,4
9512,29.0,fit,NaN,rarely,never,student,70.0,-1.0,0,gay,likes dogs and has cats,NaN,m,aries,no,single,1.0,1.0,13,3
9513,49.0,bad,NaN,rarely,never,graduated,64.0,-1.0,-1,straight,likes dogs and likes cats,NaN,f,pisces,no,single,1.0,0.0,13,6

In [57]:
df.isnull().sum()

age                              0
body_type                      848
diet                          5340
drinks                         502
drugs                         2299
education                     1055
height                           0
income                           0
last_online                      0
offspring                        0
orientation                      0
pets                          3162
religion                      3253
sex                              0
sign                          1738
smokes                         918
status                           0
number_of_fluent_languages       6
number_of_poorly_languages       6
last_online_year                 0
last_online_month                0
dtype: int64

In [58]:
df.fillna(df.median(numeric_only=True), inplace=True)

In [59]:
df.fillna(df.mode().iloc[0], inplace=True)

In [60]:
df.isnull().sum()

age                           0
body_type                     0
diet                          0
drinks                        0
drugs                         0
education                     0
height                        0
income                        0
last_online                   0
offspring                     0
orientation                   0
pets                          0
religion                      0
sex                           0
sign                          0
smokes                        0
status                        0
number_of_fluent_languages    0
number_of_poorly_languages    0
last_online_year              0
last_online_month             0
dtype: int64

In [61]:
# sayısal ve sözel sütunlardaki boşlukları doldurduk

In [62]:
# Veri seti hazırlama tamamlandı.

In [63]:
generation =[]
for i in df["age"].values:
    if (i>=18) and (i<=32):
        generation .append("Millennial")
    elif (i>=33) and (i<=47):
        generation .append("Gen X-er")
    elif (48>=33) and (i<=70):
        generation .append("Boomers")
    else:
        generation .append("Unkown")

df["generation "]=generation

In [64]:
df.head()

,age,body_type,diet,drinks,drugs,education,height,income,last_online,offspring,...,religion,sex,sign,smokes,status,number_of_fluent_languages,number_of_poorly_languages,last_online_year,last_online_month,generation
0,22.0,curvy,anything,socially,never,student,75.0,-1.0,2012-06-28-20-30,0,...,agnosticism,m,gemini,sometimes,single,1.0,0.0,13,6,Millennial
1,35.0,fit,anything,often,sometimes,student,70.0,80000.0,2012-06-29-21-41,0,...,agnosticism,m,cancer,no,single,1.0,2.0,13,6,Gen X-er
2,38.0,fit,anything,socially,never,graduated,68.0,-1.0,2012-06-27-09-10,-1,...,agnosticism,m,pisces,no,available,1.0,0.0,13,6,Gen X-er
3,23.0,fit,anything,socially,never,student,71.0,20000.0,2012-06-28-14-22,0,...,agnosticism,m,pisces,no,single,1.0,1.0,13,6,Millennial
4,29.0,fit,anything,socially,never,graduated,66.0,-1.0,2012-06-27-21-26,-1,...,agnosticism,m,aquarius,no,single,1.0,0.0,13,6,Millennial

In [65]:
df.corr(numeric_only= True)

,age,height,income,offspring,number_of_fluent_languages,number_of_poorly_languages,last_online_year,last_online_month
age,1.000000,-0.022078,0.011424,0.290501,-0.024795,-0.001559,-0.015792,-0.003527
height,-0.022078,1.000000,0.073105,-0.046832,0.015458,0.036414,-0.016633,-0.010858
income,0.011424,0.073105,1.000000,0.013989,0.039186,0.028577,0.009376,0.002043
offspring,0.290501,-0.046832,0.013989,1.000000,-0.012560,0.001772,-0.100665,-0.020442
number_of_fluent_languages,-0.024795,0.015458,0.039186,-0.012560,1.000000,0.067774,-0.003813,-0.006593
number_of_poorly_languages,-0.001559,0.036414,0.028577,0.001772,0.067774,1.000000,-0.034827,-0.006141
last_online_year,-0.015792,-0.016633,0.009376,-0.100665,-0.003813,-0.034827,1.000000,0.685183
last_online_month,-0.003527,-0.010858,0.002043,-0.020442,-0.006593,-0.006141,0.685183,1.000000

In [66]:
df=pd.get_dummies(df,drop_first=True)

In [69]:
df.head()

,age,height,income,offspring,number_of_fluent_languages,number_of_poorly_languages,last_online_year,last_online_month,body_type_curvy,body_type_fit,diet_other,diet_vegan,diet_vegetarian,drinks_not at all,drinks_often,drinks_rarely,drinks_socially,drinks_very often,drugs_often,drugs_sometimes,education_graduated,education_student,last_online_2011-06-27-22-05,last_online_2011-06-28-14-10,last_online_2011-06-29-20-30,last_online_2011-06-29-20-34,last_online_2011-06-29-20-38,last_online_2011-06-30-04-52,last_online_2011-06-30-20-03,last_online_2011-06-30-23-38,last_online_2011-07-01-05-33,last_online_2011-07-01-07-34,last_online_2011-07-01-20-46,last_online_2011-07-01-21-21,last_online_2011-07-02-19-40,last_online_2011-07-02-23-17,last_online_2011-07-03-15-25,last_online_2011-07-03-16-23,last_online_2011-07-04-10-18,last_online_2011-07-04-14-06,last_online_2011-07-05-07-21,last_online_2011-07-05-08-39,last_online_2011-07-05-20-26,last_online_2011-07-06-08-47,last_online_2011-07-06-23-19,last_online_2011-07-06-23-49,last_online_2011-07-07-00-15,last_online_2011-07-07-09-07,last_online_2011-07-07-15-11,last_online_2011-07-07-22-00,...,last_online_2012-06-30-08-13,last_online_2012-06-30-08-15,last_online_2012-06-30-08-16,last_online_2012-06-30-08-23,orientation_gay,orientation_straight,pets_dislikes dogs,pets_dislikes dogs and dislikes cats,pets_dislikes dogs and has cats,pets_dislikes dogs and likes cats,pets_has cats,pets_has dogs,pets_has dogs and dislikes cats,pets_has dogs and has cats,pets_has dogs and likes cats,pets_likes cats,pets_likes dogs,pets_likes dogs and dislikes cats,pets_likes dogs and has cats,pets_likes dogs and likes cats,religion_atheism,religion_buddhism,religion_catholicism,religion_christianity,religion_hinduism,religion_islam,religion_judaism,religion_other,sex_m,sign_aries,sign_cancer,sign_capricorn,sign_gemini,sign_leo,sign_libra,sign_pisces,sign_sagittarius,sign_scorpio,sign_taurus,sign_virgo,smokes_sometimes,smokes_trying to quit,smokes_when drinking,smokes_yes,status_married,status_seeing someone,status_single,generation _Gen X-er,generation _Millennial,generation _Unkown
0,22.0,75.0,-1.0,0,1.0,0.0,13,6,True,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,True,False
1,35.0,70.0,80000.0,0,1.0,2.0,13,6,False,True,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
2,38.0,68.0,-1.0,-1,1.0,0.0,13,6,False,True,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False
3,23.0,71.0,20000.0,0,1.0,1.0,13,6,False,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False
4,29.0,66.0,-1.0,-1,1.0,0.0,13,6,False,True,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False

### Model

In [67]:
# Algo test

In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns",100)

from sklearn.linear_model import LinearRegression,SGDRegressor,Ridge,Lasso,ElasticNet
from sklearn.neighbors import KNeighborsRegressor, RadiusNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor,AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor, plot_tree, ExtraTreeRegressor
#pip install xgboost
from xgboost import XGBRegressor
from sklearn.svm import SVR

from sklearn.neural_network import MLPRegressor

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

def algo_test(x,y):
        #Bütün modelleri tanımlıyorum
        L=LinearRegression()
        R=Ridge()
        Lass=Lasso()
        E=ElasticNet()
        sgd=SGDRegressor()
        ETR=ExtraTreeRegressor()
        GBR=GradientBoostingRegressor()
        kn=KNeighborsRegressor()
        rkn=RadiusNeighborsRegressor(radius=1.0)
        ada=AdaBoostRegressor()
        dt=DecisionTreeRegressor()
        xgb=XGBRegressor()
        svr=SVR()
        mlp_regressor = MLPRegressor()

       
        
        algos=[L,R,Lass,E,sgd,ETR,GBR,ada,kn,dt,xgb,svr,mlp_regressor]
        algo_names=['Linear','Ridge','Lasso','ElasticNet','SGD','Extra Tree','Gradient Boosting',
                    'KNeighborsRegressor','AdaBoost','Decision Tree','XGBRegressor','SVR','mlp_regressor']
        x=MinMaxScaler().fit_transform(x)
        x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=.20,random_state=42)
        
        r_squared= []
        rmse= []
        mae= []
        
        #Hata ve doğruluk oranlarını bir tablo haline getirmek için bir dataframe oluşturuyorum
        result=pd.DataFrame(columns=['R_Squared','RMSE','MAE'],index=algo_names)
        
        
        for algo in algos:
            p=algo.fit(x_train,y_train).predict(x_test)
            r_squared.append(r2_score(y_test,p))
            rmse.append(mean_squared_error(y_test,p)**.5)
            mae.append(mean_absolute_error(y_test,p))
        
            

        #result adlı tabloya doğruluk ve hata oranlarımı yerleştiriyorum
        result.R_Squared=r_squared
        result.RMSE=rmse
        result.MAE=mae
        
       #oluşturduğum result tablosunu doğruluk oranına (r2_score) göre sıralayıp dönüyor
        rtable=result.sort_values('R_Squared',ascending=False)
        return rtable