In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [3]:
df = pd.DataFrame({
    'color': ['red','green','blue','red','green'],
    'size': ['small','medium','large','medium','small'],
    'price': [10,15,20,8,12]
})

In [4]:
df

   color    size  price
0    red   small     10
1  green  medium     15
2   blue   large     20
3    red  medium      8
4  green   small     12

In [5]:
le = LabelEncoder()

In [6]:
df['size2'] = le.fit_transform(df['size'] ) ## bedenleri sıralayabileceğimiz için le kullandık. 0 dan 2 ye

In [7]:
df

   color    size  price  size2
0    red   small     10      2
1  green  medium     15      1
2   blue   large     20      0
3    red  medium      8      1
4  green   small     12      2

In [8]:
oe = OneHotEncoder()

In [10]:
oe.fit_transform(df[['color']]).toarray() # renklerde üstünlük olmadığı için bunu kullandık

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [ ]:
# Aritmetik İşlemler