# ANN -  DEEP Learning - Concrete Compressive Strength - Regression  & Classification Project

# Beton Basınç Dayanımı Tahmini

Bu proje, betonun **basınç dayanımını** karışımındaki malzemeler ve kürlenme süresine göre tahmin etmeyi ve betonun yapısal sınıfını sınıflandırmayı amaçlamaktadır. Veri seti [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Concrete+Compressive+Strength) kaynağından alınmıştır.

## Amaçlar
1. **Regresyon:** Çimento, Slag, Uçucu Kül (FlyAsh), Su, Plastiklaştırıcı, Grov ve İnce Agrega ile Betonun yaşına (Age) bağlı olarak basınç dayanımını (MPa) tahmin etmek.
2. **Sınıflandırma:** Aynı özellikleri kullanarak betonun sınıfını tahmin etmek (non-structural, residential, commercial, high-strength).

## Yaklaşım
- Veri ön işleme ve özellik-hedef ayrımı.
- Eğitim-test veri seti bölünmesi ve ölçekleme.
- **klasik makine öğrenmesi algoritmaları** ve **Derin Öğrenme (TensorFlow/Keras)** kullanılarak regresyon ve sınıflandırma modelleri geliştirme.
- Model performansını regresyon için R² ve MSE, sınıflandırma için doğruluk (accuracy) ile değerlendirme.

Bu temel model, beton dayanımı tahmini ve sınıflandırması için performans kriterlerini belirlemektedir.

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('Concrete_Data.xls')

In [3]:
df.head()

,Cement (component 1)(kg in a m^3 mixture),Blast Furnace Slag (component 2)(kg in a m^3 mixture),Fly Ash (component 3)(kg in a m^3 mixture),Water (component 4)(kg in a m^3 mixture),Superplasticizer (component 5)(kg in a m^3 mixture),Coarse Aggregate (component 6)(kg in a m^3 mixture),Fine Aggregate (component 7)(kg in a m^3 mixture),Age (day),"Concrete compressive strength(MPa, megapascals)"
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075

In [4]:
df.shape

(1030, 9)

In [5]:
df.isnull().sum()

Cement (component 1)(kg in a m^3 mixture)                0
Blast Furnace Slag (component 2)(kg in a m^3 mixture)    0
Fly Ash (component 3)(kg in a m^3 mixture)               0
Water  (component 4)(kg in a m^3 mixture)                0
Superplasticizer (component 5)(kg in a m^3 mixture)      0
Coarse Aggregate  (component 6)(kg in a m^3 mixture)     0
Fine Aggregate (component 7)(kg in a m^3 mixture)        0
Age (day)                                                0
Concrete compressive strength(MPa, megapascals)          0
dtype: int64

In [6]:
df.isna().sum()

Cement (component 1)(kg in a m^3 mixture)                0
Blast Furnace Slag (component 2)(kg in a m^3 mixture)    0
Fly Ash (component 3)(kg in a m^3 mixture)               0
Water  (component 4)(kg in a m^3 mixture)                0
Superplasticizer (component 5)(kg in a m^3 mixture)      0
Coarse Aggregate  (component 6)(kg in a m^3 mixture)     0
Fine Aggregate (component 7)(kg in a m^3 mixture)        0
Age (day)                                                0
Concrete compressive strength(MPa, megapascals)          0
dtype: int64

In [7]:

df.columns = ['Cement', 'Slag', 'FlyAsh', 'Water', 'Plasticizer',  'CoarseAgg', 'FineAgg', 'Age', 'Strength']

In [8]:
df.head()

,Cement,Slag,FlyAsh,Water,Plasticizer,CoarseAgg,FineAgg,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075

In [9]:
X = df.drop("Strength", axis=1)
y = df["Strength"]

In [10]:
# Regression Model

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns",100)

from sklearn.linear_model import LinearRegression,SGDRegressor,Ridge,Lasso,ElasticNet
from sklearn.neighbors import KNeighborsRegressor, RadiusNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor,AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor, plot_tree, ExtraTreeRegressor
#pip install xgboost
from xgboost import XGBRegressor
from sklearn.svm import SVR

from sklearn.neural_network import MLPRegressor

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

def algo_test(x,y):
        #Bütün modelleri tanımlıyorum
        L=LinearRegression()
        R=Ridge()
        Lass=Lasso()
        E=ElasticNet()
        sgd=SGDRegressor()
        ETR=ExtraTreeRegressor()
        GBR=GradientBoostingRegressor()
        kn=KNeighborsRegressor()
        rkn=RadiusNeighborsRegressor(radius=1.0)
        ada=AdaBoostRegressor()
        dt=DecisionTreeRegressor()
        xgb=XGBRegressor()
        svr=SVR()
        mlp_regressor = MLPRegressor()

       
        
        algos=[L,R,Lass,E,sgd,ETR,GBR,ada,kn,dt,xgb,svr,mlp_regressor]
        algo_names=['Linear','Ridge','Lasso','ElasticNet','SGD','Extra Tree','Gradient Boosting',
                    'KNeighborsRegressor','AdaBoost','Decision Tree','XGBRegressor','SVR','mlp_regressor']
        x=MinMaxScaler().fit_transform(x)
        x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=.20,random_state=42)
        
        r_squared= []
        rmse= []
        mae= []
        
        #Hata ve doğruluk oranlarını bir tablo haline getirmek için bir dataframe oluşturuyorum
        result=pd.DataFrame(columns=['R_Squared','RMSE','MAE'],index=algo_names)
        
        
        for algo in algos:
            p=algo.fit(x_train,y_train).predict(x_test)
            r_squared.append(r2_score(y_test,p))
            rmse.append(mean_squared_error(y_test,p)**.5)
            mae.append(mean_absolute_error(y_test,p))
        
            

        #result adlı tabloya doğruluk ve hata oranlarımı yerleştiriyorum
        result.R_Squared=r_squared
        result.RMSE=rmse
        result.MAE=mae
        
       #oluşturduğum result tablosunu doğruluk oranına (r2_score) göre sıralayıp dönüyor
        rtable=result.sort_values('R_Squared',ascending=False)
        return rtable

In [12]:
algo_test(X,y)

                     R_Squared       RMSE        MAE
XGBRegressor          0.904393   4.963481   3.074486
Gradient Boosting     0.880893   5.539991   4.096813
Decision Tree         0.794231   7.281673   4.604012
KNeighborsRegressor   0.748444   8.051167   6.617138
Extra Tree            0.724255   8.429370   5.157328
AdaBoost              0.684380   9.018273   6.981992
Linear                0.627542   9.796708   7.745393
Ridge                 0.625482   9.823755   7.864789
SGD                   0.621429   9.876773   7.919214
SVR                   0.606672  10.067426   8.097911
mlp_regressor         0.469880  11.687680   9.625494
Lasso                 0.188441  14.461104  11.926352
ElasticNet            0.055276  15.602480  12.708092

## Deep Learning

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import r2_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
# --- ANN Modeli ---
model = Sequential()
model.add(Dense(64, activation='relu', input_dim=X_train.shape[1]))  # Giriş katmanı + 1. gizli katman
model.add(Dense(32, activation='relu'))                              # 2. gizli katman
model.add(Dense(1))

In [17]:
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [18]:
# --- Eğitim ---
history = model.fit(X_train, y_train, validation_split=0.2,
                    epochs=100, batch_size=16, verbose=1)

Epoch 1/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 1517.2498 - mae: 34.9405 - val_loss: 1395.5171 - val_mae: 34.0720
Epoch 2/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1248.8170 - mae: 31.1519 - val_loss: 1034.0132 - val_mae: 28.6264
Epoch 3/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 793.7803 - mae: 23.3857 - val_loss: 538.3842 - val_mae: 19.3621
Epoch 4/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 359.5562 - mae: 14.9371 - val_loss: 238.6539 - val_mae: 12.5775
Epoch 5/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 227.1694 - mae: 12.1595 - val_loss: 178.4946 - val_mae: 11.1703
Epoch 6/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 205.4725 - mae: 11.5229 - val_loss: 166.3389 - val_mae: 10.8276
Epoch 7/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 191.3969 - mae: 11.2613 - val_loss: 160.3027 - val_mae: 10.6635
Epoch 8/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 179.1775 - mae: 10.9159 - val_loss: 152.2572 - val_mae: 10.3962
Epoch 9/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 171.2894 - mae: 10.7149 - val_loss: 147.0690 - val_mae: 10.2303
Epoch 10/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 163.6048 - mae: 10.4555 - val_loss: 141.5781 - val_mae: 10.0323
Epoch 11/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 159.3189 - mae: 10.2679 - val_loss: 139.8823 - val_mae: 9.9183
Epoch 12/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 154.0033 - mae: 10.1062 - val_loss: 134.7640 - val_mae: 9.7157
Epoch 13/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 149.9440 - mae: 9.9698 - val_loss: 133.2401 - val_mae: 9.6383
Epoch 14/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 148.0124 - mae: 9.8768 - val_loss: 131.5829 - val_mae: 9.5545
Epoch 15/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 143.0211 - mae: 9.7489 - val_loss: 129.0251 - val_mae: 9.4618
Epoch 16/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 140.5125 - mae: 9.6942 - val_loss: 127.2578 - val_mae: 9.3750
Epoch 17/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 137.7035 - mae: 9.5496 - val_loss: 126.7748 - val_mae: 9.3526
Epoch 18/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 136.0205 - mae: 9.4892 - val_loss: 125.9295 - val_mae: 9.3038
Epoch 19/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 134.1535 - mae: 9.4298 - val_loss: 123.8304 - val_mae: 9.1915
Epoch 20/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 132.1561 - mae: 9.3326 - val_loss: 123.5508 - val_mae: 9.1652
Epoch 21/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 131.4837 - mae: 9.3239 - val_loss: 124.1688 - val_mae: 9.2016
Epoch 22/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 128.3139 - mae: 9.2250 - val_loss: 120.0260 - val_mae: 9.0020
Epoch 23/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 127.8442 - mae: 9.1946 - val_loss: 118.5084 - val_mae: 8.8867
Epoch 24/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 126.2401 - mae: 9.1134 - val_loss: 118.3471 - val_mae: 8.8988
Epoch 25/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 124.0074 - mae: 9.0331 - val_loss: 118.3992 - val_mae: 8.8887
Epoch 26/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 123.3074 - mae: 9.0290 - val_loss: 117.3788 - val_mae: 8.8410
Epoch 27/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 121.2928 - mae: 8.9575 - val_loss: 115.7712 - val_mae: 8.7687
Epoch 28/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 120.6202 - mae: 8.9006 - val_loss: 115.9514 - val_mae: 8.7631
Epoch 29/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 118.9584 - mae: 8.8412 - val_loss: 114.3562 - val_mae: 8.6624
Epoch 30/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 117.4652 - mae: 8.7667 - val_loss: 113.8881 - val_mae: 8.6723
Epoch 31/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 115.6611 - mae: 8.7194 - val_loss: 113.8414 - val_mae: 8.6538
Epoch 32/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 114.5485 - mae: 8.6744 - val_loss: 112.1375 - val_mae: 8.5184
Epoch 33/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 113.2805 - mae: 8.5924 - val_loss: 110.9322 - val_mae: 8.4940
Epoch 34/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 111.1021 - mae: 8.5002 - val_loss: 110.3293 - val_mae: 8.4579
Epoch 35/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 108.9013 - mae: 8.4033 - val_loss: 109.9249 - val_mae: 8.4109
Epoch 36/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 107.6997 - mae: 8.3537 - val_loss: 108.4008 - val_mae: 8.3101
Epoch 37/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 105.9996 - mae: 8.2737 - val_loss: 106.6070 - val_mae: 8.1920
Epoch 38/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 104.0775 - mae: 8.1952 - val_loss: 105.8016 - val_mae: 8.2264
Epoch 39/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 101.6906 - mae: 8.1185 - val_loss: 105.4796 - val_mae: 8.2374
Epoch 40/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 100.8987 - mae: 8.0747 - val_loss: 103.4214 - val_mae: 8.0889
Epoch 41/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 96.8874 - mae: 7.8797 - val_loss: 102.5083 - val_mae: 8.0536
Epoch 42/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 94.5519 - mae: 7.7644 - val_loss: 99.6755 - val_mae: 7.8938
Epoch 43/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 92.4671 - mae: 7.6569 - val_loss: 99.6770 - val_mae: 7.9420
Epoch 44/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 90.5169 - mae: 7.5853 - val_loss: 95.8694 - val_mae: 7.6699
Epoch 45/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 89.4666 - mae: 7.5093 - val_loss: 94.0150 - val_mae: 7.5369
Epoch 46/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 85.8050 - mae: 7.3383 - val_loss: 92.1231 - val_mae: 7.5454
Epoch 47/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 83.4137 - mae: 7.2453 - val_loss: 89.2793 - val_mae: 7.3481
Epoch 48/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 81.8535 - mae: 7.1459 - val_loss: 87.2549 - val_mae: 7.2974
Epoch 49/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 77.8281 - mae: 6.9529 - val_loss: 87.0421 - val_mae: 7.4140
Epoch 50/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 76.0579 - mae: 6.8761 - val_loss: 84.1045 - val_mae: 7.0718
Epoch 51/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 74.0116 - mae: 6.7707 - val_loss: 79.3952 - val_mae: 6.9254
Epoch 52/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 70.6411 - mae: 6.5802 - val_loss: 78.1019 - val_mae: 6.8734
Epoch 53/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 68.7399 - mae: 6.4882 - val_loss: 76.1289 - val_mae: 6.8102
Epoch 54/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 66.8935 - mae: 6.3945 - val_loss: 73.9418 - val_mae: 6.6821
Epoch 55/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 64.8425 - mae: 6.2690 - val_loss: 71.6240 - val_mae: 6.5795
Epoch 56/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 63.0808 - mae: 6.1505 - val_loss: 69.1818 - val_mae: 6.4283
Epoch 57/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 61.2411 - mae: 6.0655 - val_loss: 68.9317 - val_mae: 6.4468
Epoch 58/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 59.6776 - mae: 5.9612 - val_loss: 65.7246 - val_mae: 6.2664
Epoch 59/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 57.7080 - mae: 5.8412 - val_loss: 64.0535 - val_mae: 6.1995
Epoch 60/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 56.5559 - mae: 5.8056 - val_loss: 63.4989 - val_mae: 6.0738
Epoch 61/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55.4516 - mae: 5.6178 - val_loss: 61.7962 - val_mae: 6.0169
Epoch 62/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54.0935 - mae: 5.6159 - val_loss: 61.9820 - val_mae: 5.8827
Epoch 63/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 53.1188 - mae: 5.5192 - val_loss: 58.6490 - val_mae: 5.7661
Epoch 64/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51.2948 - mae: 5.4476 - val_loss: 56.4015 - val_mae: 5.7217
Epoch 65/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50.2384 - mae: 5.4008 - val_loss: 57.2398 - val_mae: 5.6084
Epoch 66/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 48.1795 - mae: 5.2222 - val_loss: 55.4654 - val_mae: 5.7401
Epoch 67/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 47.8672 - mae: 5.1938 - val_loss: 53.1451 - val_mae: 5.4620
Epoch 68/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 46.3878 - mae: 5.1756 - val_loss: 50.5682 - val_mae: 5.3250
Epoch 69/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45.1397 - mae: 5.0828 - val_loss: 51.3582 - val_mae: 5.2986
Epoch 70/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 45.1690 - mae: 5.0481 - val_loss: 50.0497 - val_mae: 5.2196
Epoch 71/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 43.2593 - mae: 4.9762 - val_loss: 49.0531 - val_mae: 5.1889
Epoch 72/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 43.0207 - mae: 4.9643 - val_loss: 48.3736 - val_mae: 5.2106
Epoch 73/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 42.9683 - mae: 4.9737 - val_loss: 49.7054 - val_mae: 5.2873
Epoch 74/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 41.3569 - mae: 4.8876 - val_loss: 47.0226 - val_mae: 5.1217
Epoch 75/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 40.3964 - mae: 4.7927 - val_loss: 46.7968 - val_mae: 5.1361
Epoch 76/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 40.4402 - mae: 4.8095 - val_loss: 45.2130 - val_mae: 4.9298
Epoch 77/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 39.4508 - mae: 4.7503 - val_loss: 46.6148 - val_mae: 5.1201
Epoch 78/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 38.3385 - mae: 4.6528 - val_loss: 44.4868 - val_mae: 4.8468
Epoch 79/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37.8670 - mae: 4.6470 - val_loss: 44.0663 - val_mae: 4.8463
Epoch 80/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37.4716 - mae: 4.5573 - val_loss: 44.1065 - val_mae: 4.8413
Epoch 81/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37.5412 - mae: 4.6094 - val_loss: 43.5628 - val_mae: 4.8232
Epoch 82/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 36.8115 - mae: 4.6252 - val_loss: 42.7411 - val_mae: 4.7503
Epoch 83/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 35.4756 - mae: 4.4704 - val_loss: 42.0518 - val_mae: 4.6780
Epoch 84/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 35.1574 - mae: 4.4808 - val_loss: 42.5146 - val_mae: 4.7137
Epoch 85/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 34.9600 - mae: 4.4533 - val_loss: 41.1409 - val_mae: 4.6368
Epoch 86/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 34.3249 - mae: 4.4453 - val_loss: 41.8623 - val_mae: 4.7304
Epoch 87/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 33.9108 - mae: 4.4119 - val_loss: 40.4602 - val_mae: 4.5987
Epoch 88/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 33.4132 - mae: 4.4088 - val_loss: 41.4473 - val_mae: 4.7534
Epoch 89/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32.7346 - mae: 4.3289 - val_loss: 40.9106 - val_mae: 4.6764
Epoch 90/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32.7470 - mae: 4.3666 - val_loss: 39.9902 - val_mae: 4.6457
Epoch 91/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 31.7047 - mae: 4.2959 - val_loss: 38.9333 - val_mae: 4.5279
Epoch 92/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32.2097 - mae: 4.2590 - val_loss: 39.8340 - val_mae: 4.6387
Epoch 93/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 31.8847 - mae: 4.2848 - val_loss: 39.8390 - val_mae: 4.6479
Epoch 94/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30.9521 - mae: 4.2235 - val_loss: 40.1294 - val_mae: 4.6977
Epoch 95/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30.9629 - mae: 4.2133 - val_loss: 39.4534 - val_mae: 4.6182
Epoch 96/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30.2553 - mae: 4.2049 - val_loss: 37.7718 - val_mae: 4.4212
Epoch 97/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29.7202 - mae: 4.1580 - val_loss: 39.8199 - val_mae: 4.6950
Epoch 98/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30.2156 - mae: 4.1667 - val_loss: 39.2710 - val_mae: 4.6527
Epoch 99/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29.2275 - mae: 4.1368 - val_loss: 38.0420 - val_mae: 4.5025
Epoch 100/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 29.1573 - mae: 4.0613 - val_loss: 38.0989 - val_mae: 4.5041

In [19]:
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
print(f"Test R² Score: {r2:.4f}")

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
Test R² Score: 0.8273

## 2. Problem

In [20]:
# --- Kategorik hedef oluştur ---
def strength_classifer(x):
    if x < 17.0:
        return "non-structural"
    elif x < 28.0:
        return "residential"
    elif x < 70.0:
        return "commercial"
    else:
        return "high-strength"

In [21]:
df["ConcreteClass"] = df.Strength.apply(strength_classifer)
df.drop("Strength", axis=1, inplace=True)

In [22]:
X = pd.get_dummies(df.drop("ConcreteClass", axis=1), drop_first=True)  # tüm kategorik encode
y = LabelEncoder().fit_transform(df["ConcreteClass"])

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
model = Sequential([
    Dense(64, activation='relu', input_dim=X_train.shape[1]),
    Dense(32, activation='relu'),
    Dense(len(set(y)), activation='softmax')  # sınıf sayısı kadar çıkış
])

In [26]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [27]:
history = model.fit(X_train, y_train, validation_split=0.2, epochs=100, batch_size=16, verbose=1)

Epoch 1/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5615 - loss: 1.1291 - val_accuracy: 0.6424 - val_loss: 0.9363
Epoch 2/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6070 - loss: 0.9529 - val_accuracy: 0.6424 - val_loss: 0.8514
Epoch 3/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6373 - loss: 0.8718 - val_accuracy: 0.6545 - val_loss: 0.7961
Epoch 4/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6798 - loss: 0.8033 - val_accuracy: 0.6788 - val_loss: 0.7478
Epoch 5/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6980 - loss: 0.7448 - val_accuracy: 0.6909 - val_loss: 0.7035
Epoch 6/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7102 - loss: 0.6940 - val_accuracy: 0.7091 - val_loss: 0.6703
Epoch 7/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7329 - loss: 0.6588 - val_accuracy: 0.7152 - val_loss: 0.6471
Epoch 8/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7542 - loss: 0.6315 - val_accuracy: 0.7576 - val_loss: 0.6262
Epoch 9/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7709 - loss: 0.6008 - val_accuracy: 0.7515 - val_loss: 0.6186
Epoch 10/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7815 - loss: 0.5763 - val_accuracy: 0.7636 - val_loss: 0.5899
Epoch 11/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8027 - loss: 0.5489 - val_accuracy: 0.8000 - val_loss: 0.5758
Epoch 12/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8012 - loss: 0.5292 - val_accuracy: 0.8000 - val_loss: 0.5647
Epoch 13/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8179 - loss: 0.5073 - val_accuracy: 0.7758 - val_loss: 0.5578
Epoch 14/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8164 - loss: 0.4882 - val_accuracy: 0.8061 - val_loss: 0.5306
Epoch 15/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8194 - loss: 0.4786 - val_accuracy: 0.8061 - val_loss: 0.5386
Epoch 16/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8285 - loss: 0.4590 - val_accuracy: 0.7697 - val_loss: 0.5183
Epoch 17/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8331 - loss: 0.4448 - val_accuracy: 0.7879 - val_loss: 0.5125
Epoch 18/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8452 - loss: 0.4295 - val_accuracy: 0.7879 - val_loss: 0.5103
Epoch 19/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8483 - loss: 0.4172 - val_accuracy: 0.8000 - val_loss: 0.4977
Epoch 20/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8483 - loss: 0.4078 - val_accuracy: 0.8000 - val_loss: 0.4990
Epoch 21/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8619 - loss: 0.3932 - val_accuracy: 0.7879 - val_loss: 0.4883
Epoch 22/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8619 - loss: 0.3895 - val_accuracy: 0.8061 - val_loss: 0.4761
Epoch 23/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8649 - loss: 0.3771 - val_accuracy: 0.7758 - val_loss: 0.4697
Epoch 24/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8741 - loss: 0.3719 - val_accuracy: 0.8061 - val_loss: 0.4817
Epoch 25/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8710 - loss: 0.3561 - val_accuracy: 0.8061 - val_loss: 0.4670
Epoch 26/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8725 - loss: 0.3520 - val_accuracy: 0.8182 - val_loss: 0.4650
Epoch 27/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8680 - loss: 0.3505 - val_accuracy: 0.8121 - val_loss: 0.4478
Epoch 28/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8847 - loss: 0.3369 - val_accuracy: 0.8182 - val_loss: 0.4608
Epoch 29/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8907 - loss: 0.3279 - val_accuracy: 0.8121 - val_loss: 0.4499
Epoch 30/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8832 - loss: 0.3233 - val_accuracy: 0.8121 - val_loss: 0.4400
Epoch 31/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8892 - loss: 0.3163 - val_accuracy: 0.8061 - val_loss: 0.4393
Epoch 32/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8862 - loss: 0.3110 - val_accuracy: 0.8121 - val_loss: 0.4354
Epoch 33/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8877 - loss: 0.3131 - val_accuracy: 0.8182 - val_loss: 0.4540
Epoch 34/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9014 - loss: 0.3011 - val_accuracy: 0.8000 - val_loss: 0.4451
Epoch 35/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8923 - loss: 0.2952 - val_accuracy: 0.8061 - val_loss: 0.4254
Epoch 36/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8892 - loss: 0.2979 - val_accuracy: 0.8061 - val_loss: 0.4318
Epoch 37/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8832 - loss: 0.3041 - val_accuracy: 0.8242 - val_loss: 0.4271
Epoch 38/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8968 - loss: 0.2836 - val_accuracy: 0.8121 - val_loss: 0.4241
Epoch 39/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8938 - loss: 0.2797 - val_accuracy: 0.8303 - val_loss: 0.4206
Epoch 40/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9029 - loss: 0.2744 - val_accuracy: 0.8061 - val_loss: 0.4273
Epoch 41/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9074 - loss: 0.2697 - val_accuracy: 0.8182 - val_loss: 0.4308
Epoch 42/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9014 - loss: 0.2703 - val_accuracy: 0.8061 - val_loss: 0.4274
Epoch 43/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9150 - loss: 0.2594 - val_accuracy: 0.8182 - val_loss: 0.4273
Epoch 44/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8968 - loss: 0.2590 - val_accuracy: 0.8242 - val_loss: 0.4374
Epoch 45/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9029 - loss: 0.2574 - val_accuracy: 0.8182 - val_loss: 0.4056
Epoch 46/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9059 - loss: 0.2491 - val_accuracy: 0.8182 - val_loss: 0.4187
Epoch 47/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9105 - loss: 0.2455 - val_accuracy: 0.8061 - val_loss: 0.4241
Epoch 48/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9135 - loss: 0.2451 - val_accuracy: 0.8061 - val_loss: 0.4406
Epoch 49/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9120 - loss: 0.2449 - val_accuracy: 0.8242 - val_loss: 0.4287
Epoch 50/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9120 - loss: 0.2410 - val_accuracy: 0.8303 - val_loss: 0.4221
Epoch 51/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9135 - loss: 0.2383 - val_accuracy: 0.8061 - val_loss: 0.4205
Epoch 52/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9074 - loss: 0.2367 - val_accuracy: 0.8303 - val_loss: 0.4120
Epoch 53/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9196 - loss: 0.2272 - val_accuracy: 0.8061 - val_loss: 0.4251
Epoch 54/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9165 - loss: 0.2274 - val_accuracy: 0.8364 - val_loss: 0.4174
Epoch 55/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9165 - loss: 0.2292 - val_accuracy: 0.8182 - val_loss: 0.4161
Epoch 56/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9074 - loss: 0.2218 - val_accuracy: 0.8364 - val_loss: 0.4267
Epoch 57/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9120 - loss: 0.2169 - val_accuracy: 0.8303 - val_loss: 0.4321
Epoch 58/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9226 - loss: 0.2138 - val_accuracy: 0.8182 - val_loss: 0.4327
Epoch 59/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9165 - loss: 0.2234 - val_accuracy: 0.8242 - val_loss: 0.4228
Epoch 60/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9196 - loss: 0.2125 - val_accuracy: 0.8182 - val_loss: 0.4166
Epoch 61/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9256 - loss: 0.2156 - val_accuracy: 0.8303 - val_loss: 0.4169
Epoch 62/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9272 - loss: 0.2110 - val_accuracy: 0.8182 - val_loss: 0.4280
Epoch 63/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9165 - loss: 0.2105 - val_accuracy: 0.7879 - val_loss: 0.4347
Epoch 64/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9302 - loss: 0.2009 - val_accuracy: 0.8303 - val_loss: 0.4268
Epoch 65/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9272 - loss: 0.2012 - val_accuracy: 0.8242 - val_loss: 0.4038
Epoch 66/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9317 - loss: 0.1966 - val_accuracy: 0.8182 - val_loss: 0.4231
Epoch 67/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9272 - loss: 0.1944 - val_accuracy: 0.8242 - val_loss: 0.4211
Epoch 68/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9165 - loss: 0.2064 - val_accuracy: 0.8545 - val_loss: 0.3992
Epoch 69/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9302 - loss: 0.1894 - val_accuracy: 0.8000 - val_loss: 0.4362
Epoch 70/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9211 - loss: 0.1942 - val_accuracy: 0.8242 - val_loss: 0.4200
Epoch 71/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9272 - loss: 0.1914 - val_accuracy: 0.8182 - val_loss: 0.4281
Epoch 72/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9241 - loss: 0.1940 - val_accuracy: 0.8182 - val_loss: 0.4248
Epoch 73/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9393 - loss: 0.1906 - val_accuracy: 0.8303 - val_loss: 0.4466
Epoch 74/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9347 - loss: 0.1844 - val_accuracy: 0.8182 - val_loss: 0.4426
Epoch 75/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9408 - loss: 0.1811 - val_accuracy: 0.8303 - val_loss: 0.4169
Epoch 76/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9317 - loss: 0.1827 - val_accuracy: 0.8424 - val_loss: 0.4207
Epoch 77/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9378 - loss: 0.1773 - val_accuracy: 0.8424 - val_loss: 0.4231
Epoch 78/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9378 - loss: 0.1756 - val_accuracy: 0.8545 - val_loss: 0.4284
Epoch 79/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9439 - loss: 0.1678 - val_accuracy: 0.8182 - val_loss: 0.4263
Epoch 80/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9423 - loss: 0.1719 - val_accuracy: 0.8121 - val_loss: 0.4358
Epoch 81/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9454 - loss: 0.1698 - val_accuracy: 0.8364 - val_loss: 0.4150
Epoch 82/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9408 - loss: 0.1688 - val_accuracy: 0.8182 - val_loss: 0.4262
Epoch 83/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9347 - loss: 0.1715 - val_accuracy: 0.8061 - val_loss: 0.4500
Epoch 84/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9439 - loss: 0.1684 - val_accuracy: 0.8242 - val_loss: 0.4370
Epoch 85/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9545 - loss: 0.1624 - val_accuracy: 0.8303 - val_loss: 0.4323
Epoch 86/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9469 - loss: 0.1627 - val_accuracy: 0.8242 - val_loss: 0.4379
Epoch 87/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9469 - loss: 0.1588 - val_accuracy: 0.8182 - val_loss: 0.4302
Epoch 88/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9484 - loss: 0.1566 - val_accuracy: 0.8303 - val_loss: 0.4461
Epoch 89/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9423 - loss: 0.1628 - val_accuracy: 0.8182 - val_loss: 0.4247
Epoch 90/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9423 - loss: 0.1563 - val_accuracy: 0.8182 - val_loss: 0.4596
Epoch 91/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9454 - loss: 0.1611 - val_accuracy: 0.8364 - val_loss: 0.4630
Epoch 92/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9454 - loss: 0.1576 - val_accuracy: 0.8424 - val_loss: 0.4497
Epoch 93/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9393 - loss: 0.1678 - val_accuracy: 0.8242 - val_loss: 0.4399
Epoch 94/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9590 - loss: 0.1491 - val_accuracy: 0.8303 - val_loss: 0.4308
Epoch 95/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9530 - loss: 0.1463 - val_accuracy: 0.8424 - val_loss: 0.4274
Epoch 96/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9621 - loss: 0.1424 - val_accuracy: 0.8242 - val_loss: 0.4328
Epoch 97/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9530 - loss: 0.1482 - val_accuracy: 0.8121 - val_loss: 0.4359
Epoch 98/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9469 - loss: 0.1526 - val_accuracy: 0.8182 - val_loss: 0.4397
Epoch 99/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9439 - loss: 0.1459 - val_accuracy: 0.8061 - val_loss: 0.4604
Epoch 100/100
42/42 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9514 - loss: 0.1465 - val_accuracy: 0.8182 - val_loss: 0.4611

In [28]:
y_pred = model.predict(X_test).argmax(axis=1)
acc = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {acc:.4f}")

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
Test Accuracy: 0.8350